force-app/main/default/objects/Google_Drive_File_Upload_log__c/Google_Drive_File_Upload_log__c.object-meta.xml
<CustomObject>
    <label>Google Drive File Upload log</label>
    <nameField>
        <displayFormat>LN-{0000}</displayFormat>
        <label>File Upload Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Google Drive File Upload logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Google_Drive_File_Upload_log__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Google_Drive_File_Upload_log__c/fields/File_ID__c.field-meta.xml
<CustomField>
    <fullName>File_ID__c</fullName>
    <label>File ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Google_Drive_File_Upload_log__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <label>File Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Google_Drive_File_Upload_log__c/fields/SF_Source_Record_URL__c.field-meta.xml
<CustomField>
    <fullName>SF_Source_Record_URL__c</fullName>
    <label>SF Source Record URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Google_Drive_File_Upload_log__c/fields/Upload_Status__c.field-meta.xml
<CustomField>
    <fullName>Upload_Status__c</fullName>
    <label>Upload Status</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Google_Drive_File_Upload_log__c/fields/UploadedBy_Email__c.field-meta.xml
<CustomField>
    <fullName>UploadedBy_Email__c</fullName>
    <label>UploadedBy Email</label>
    <type>Email</type>
</CustomField>

metadatafullcopy/unpackaged/objects/Jitterbit_Log__c.object
<CustomObject>
    <fields>
        <fullName>Error_Warning_Details__c</fullName>
        <label>Error/Warning Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Log_Name__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>File Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <label>Jitterbit Log</label>
    <nameField>
        <label>Jitterbit Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jitterbit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Jitterbit_Log__c/fields/SF_Source_Record_URL__c.field-meta.xml
<CustomField>
    <fullName>SF_Source_Record_URL__c</fullName>
    <label>SF Source Record URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Jitterbit_Log__c/fields/UploadedBy_Email__c.field-meta.xml
<CustomField>
    <fullName>UploadedBy_Email__c</fullName>
    <label>UploadedBy Email</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/JitterBitLogTriggerHelper.cls
public with sharing class JitterBitLogTriggerHelper {
    
    @AuraEnabled    
    public static void createLogRecords( List<Jitterbit_Log__c> jitterBitLogRecordList){
        List<Jitterbit_Log__c> FileUploadLogList = new List<Jitterbit_Log__c>();
        try{
            for(Jitterbit_Log__c jitterbit : jitterBitLogRecordList){
                String jitterBitName = jitterbit.Name;
                String check = 'Upload via MuleSoft';
                if(jitterBitName.contains(check)){
                    FileUploadLogList.add(jitterbit);
                }
            }
            
            List<Google_Drive_File_Upload_log__c> newFUlogListToInsert = new List<Google_Drive_File_Upload_log__c>();
            for(Jitterbit_Log__c  jbRec: FileUploadLogList){
                
                Google_Drive_File_Upload_log__c FileUploadLog = new Google_Drive_File_Upload_log__c();
                FileUploadLog.Upload_Status__c = jbRec.Status__c;
                if(jbRec.Error_Warning_Details__c != null){
                    FileUploadLog.Error_Description__c = jbRec.Error_Warning_Details__c;
                }
                FileUploadLog.File_ID__c = jbRec.Source_System__c;
                FileUploadLog.File_Name__c = jbRec.Log_Name__c;
                FileUploadLog.Success__c = jbRec.Success__c;
                FileUploadLog.UploadedBy_Email__c = jbRec.UploadedBy_Email__c.substringBetween('(',')');
                FileUploadLog.SF_Source_Record_URL__c = jbRec.SF_Source_Record_URL__c ;//Added by Suman [To include SF source record view link]
                
                newFUlogListToInsert.add(FileUploadLog);
                
            }
            
            if(newFUlogListToInsert.size() > 0){
                insert newFUlogListToInsert;
            }
        }catch(Exception e){
            System.debug('System Exception occurred : ' + e.getTypeName());
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());   
        }
        
        
    }
    
}