force-app/main/default/objects/SharinPix_Deleted_Images__c/SharinPix_Deleted_Images__c.object-meta.xml
<CustomObject>
    <label>SharinPix Deleted Images</label>
    <nameField>
        <displayFormat>SDI-{0000}</displayFormat>
        <label>SharinPix Deleted Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SharinPix Deleted Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Album_ID__c.field-meta.xml
<CustomField>
    <fullName>Album_ID__c</fullName>
    <label>Album ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Converted_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Converted_Image_URL__c</fullName>
    <label>Converted Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Date_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Date_Uploaded__c</fullName>
    <label>Date Uploaded</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Google_Drive_ID_Edited__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_ID_Edited__c</fullName>
    <label>Google Drive ID - Edited</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Google_Drive_ID_Original__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_ID_Original__c</fullName>
    <label>Google Drive ID - Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Image_URL_Full__c.field-meta.xml
<CustomField>
    <fullName>Image_URL_Full__c</fullName>
    <label>Image URL Full</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Image_URL_Original__c.field-meta.xml
<CustomField>
    <fullName>Image_URL_Original__c</fullName>
    <label>Image URL Original</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>ATI_Job__c</referenceTo>
    <relationshipLabel>SharinPix Deleted Images</relationshipLabel>
    <relationshipName>SharinPix_Deleted_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Old_SharinPix_record_ID__c.field-meta.xml
<CustomField>
    <fullName>Old_SharinPix_record_ID__c</fullName>
    <label>Old SharinPix record ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SharinPix_Deleted_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SharinPixImageTriggerHandler.cls
public class SharinPixImageTriggerHandler {

    public static void createBackupRecords( List<sharinpix__SharinPixImage__c> deletedRecordList){
        List<SharinPix_Deleted_Images__c> sharinPixDeletedImagesList = new List<SharinPix_Deleted_Images__c>();
        
        for(sharinpix__SharinPixImage__c DeletedImage : deletedRecordList){
            SharinPix_Deleted_Images__c singleImageData = new SharinPix_Deleted_Images__c();
            singleImageData.Old_SharinPix_record_ID__c = DeletedImage.id;
            singleImageData.Job__c = DeletedImage.Job__c;
            singleImageData.Album_ID__c = DeletedImage.sharinpix__AlbumID__c;
            singleImageData.Converted_Image_URL__c = DeletedImage.Converted_Image_URL__c;
            singleImageData.Date_Uploaded__c = DeletedImage.sharinpix__DateUploaded__c;
            singleImageData.Job__c = DeletedImage.Job__c;
            singleImageData.File_Name__c = DeletedImage.sharinpix__FileName__c;
            singleImageData.Google_Drive_ID_Edited__c = DeletedImage.Google_Drive_ID_Edited__c;
            singleImageData.Google_Drive_ID_Original__c = DeletedImage.Google_Drive_ID_Original__c;
            singleImageData.Image_URL_Full__c = DeletedImage.sharinpix__ImageURLFull__c;
            singleImageData.Image_URL_Original__c = DeletedImage.sharinpix__ImageURLOriginal__c;
            singleImageData.Tags__c = DeletedImage.sharinpix__Tags__c;
            singleImageData.User__c = DeletedImage.sharinpix__User__c;
            sharinPixDeletedImagesList.add(singleImageData);
        }
        
        if(sharinPixDeletedImagesList.size() > 0){
            insert sharinPixDeletedImagesList;
        }
        
        
    }
}