metadatafullcopy/unpackaged/objects/Account_Roles__c.object
<CustomObject>
    <label>Account Roles</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Roles Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Master_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Job</label>
        <referenceTo>Master_Job__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>Field to indicate the ATI office associated with the job.
(Hidden Field) Only for Apex Triggers Code and other reports not for UI.</description>
        <formula>Office2__r.Name</formula>
        <label>Office Formula</label>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Flagstaff</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Anaheim</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Pittsburgh</fullName>
                </value>
                <value>
                    <fullName>Riverside</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>San Jose</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tuscon</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Master_Job__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Master Jobs</relationshipLabel>
        <relationshipName>Master_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Master Job</label>
    <nameField>
        <label>Master Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Office__c.object
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/classes/ObjectInserts.cls
global without sharing class ObjectInserts {
    public list<ATI_Job__c> jobList {get;set;}
    public list<Contact> contactList {get;set;}
    public list<Account> accountList {get;set;}
    public list<Master_Job__c> masterjobList {get;set;}
    public list<Property__c> propertyList {get;set;}
    public list<User> userList {get;set;}
    public list<Office__c> officeList {get;set;}
    public list<Account_Roles__c> accountroleList {get;set;}
    global Map<Id, Office__c> officeMap {get;set;}
}