metadatafullcopy/unpackaged/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Google_Drive_Folder_Ref__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Folder_Ref__c</fullName>
    <label>Google Drive Folder Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Job Name field is used on New Job VF page, used to pass along to Timberline, and used to update Opportunity Name field via &apos;Opportunity Naming Convention&apos; workflow.</description>
        <label>Job Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Manager assigned to this job</description>
        <label>Project Director</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Executive Management, Project Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobpm1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Estimating/Review</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                </value>
                <value>
                    <fullName>Billing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>XACT_File_Reopened__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>XACT File Reopened</label>
        <type>Checkbox</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATI_Job__c/fields/Google_Drive_Folder_Ref__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Folder_Ref__c</fullName>
    <label>Google Drive Folder Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Google_Drive_Sync_Configuration__c/Google_Drive_Sync_Configuration__c.object-meta.xml
<CustomObject>
    <label>Google Drive Sync Configuration</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Drive Sync Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Google_Drive_Sync_Configuration__c/fields/Folder_Name_for_Files__c.field-meta.xml
<CustomField>
    <fullName>Folder_Name_for_Files__c</fullName>
    <description>Folder will be created with this name for storing files in Google Drive</description>
    <label>Folder Name for Files</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Google_Drive_Sync_Configuration__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>ATI_Job__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Google_Drive_Sync_Configuration__c/fields/Upload_files_attachments__c.field-meta.xml
<CustomField>
    <fullName>Upload_files_attachments__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this is checked, files attached to the record, will be copied to Google drive.</description>
    <label>Files sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UploadFilesToGoogleDriveCDLTriggerTest.cls
/*******************************************************************************************
* @author           Suman
* @version          1.0 
* @date             01-Oct-2020
* @Status           In-Progress
* @Trigger Name     UploadFilesToGoogleDriveCDLTriggerTest
* @description      Test class for trigger -UploadFilesToGoogleDriveForSelObjects.
*********************************************************************************************
Version     Date      Team          Comments
*********************************************************************************************
* 1         Oct 2020    Suman        Initial Creation(JIRA AR-653)
*********************************************************************************************/
@isTest
public class UploadFilesToGoogleDriveCDLTriggerTest {
    
	@isTest
    static void testTrigger(){
        TestDataUtil.createCustomSettings_TriggerStatus();
        List<user> users = TestDataUtil.createUsersNew(2, true);
        
        //Google_Drive_Sync_Configuration__c
        Google_Drive_Sync_Configuration__c gdsc = new Google_Drive_Sync_Configuration__c(Name = 'Job', Object_API_Name__c = 'ATI_Job__c', Active__c = true, Upload_files_attachments__c= true, Folder_Name_for_Files__c='Google Docs,Notes & Attachments');
        insert gdsc;
        
        Account acc = new account(Name = 'Test Account');
        insert acc;
        
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id, Google_Drive_Folder_Ref__c='188Hde_c_ZQiFQeSZX7IxCJGSWySWFOHn' );
        insert job; 
        
        //Create Document
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = job.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
    }
    
    @isTest
    static void testTrigger1(){
        TestDataUtil.createCustomSettings_TriggerStatus();
        List<user> users = TestDataUtil.createUsersNew(2, true);
        
        //Google_Drive_Sync_Configuration__c
        //Google_Drive_Sync_Configuration__c gdsc = new Google_Drive_Sync_Configuration__c(Name = 'Job', Object_API_Name__c = 'ATI_Job__c', Active__c = true);
        //insert gdsc;
        
        Account acc = new account(Name = 'Test Account');
        insert acc;
        
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id, Google_Drive_Folder_Ref__c='188Hde_c_ZQiFQeSZX7IxCJGSWySWFOHn' );
        insert job; 
        
        //Create Document
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = job.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
    }
    
    @isTest
    static void testTrigger2(){
        TestDataUtil.createCustomSettings_TriggerStatus();
        List<user> users = TestDataUtil.createUsersNew(2, true);
        
        //Google_Drive_Sync_Configuration__c
        Google_Drive_Sync_Configuration__c gdsc = new Google_Drive_Sync_Configuration__c(Name = 'Job', Object_API_Name__c = 'ATI_Job__c', Active__c = true, Upload_files_attachments__c= true, Folder_Name_for_Files__c='Google Docs,Notes & Attachments');
        insert gdsc;
        
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id, Google_Drive_Folder_Ref__c='188Hde_c_ZQiFQeSZX7IxCJGSWySWFOHn' );
        insert job; 
        ATI_Job__c job1 = new ATI_Job__c(Name = 'Test Job1',Job_Name__c = 'Test Job1',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id, Google_Drive_Folder_Ref__c='188Hde_c_ZQiFQeSZX7IxCJGSWySWFOHn' );
        insert job1; 
        
        //Create Document
        ContentVersion cv = new ContentVersion();
        cv.Title = 'Test Document';
        cv.PathOnClient = 'TestDocument.pdf';
        cv.VersionData = Blob.valueOf('Test Content');
        cv.IsMajorVersion = true;
        Insert cv;
        //Create Document
        ContentVersion cv2 = new ContentVersion();
        cv2.Title = 'Test Document';
        cv2.PathOnClient = 'TestDocument.pdf';
        cv2.VersionData = Blob.valueOf('Test Content');
        cv2.IsMajorVersion = true;
        Insert cv2;
        //Create Document
        ContentVersion cv3 = new ContentVersion();
        cv3.Title = 'Test Document';
        cv3.PathOnClient = 'TestDocument.pdf';
        cv3.VersionData = Blob.valueOf('Test Content');
        cv3.IsMajorVersion = true;
        Insert cv3;
        
        //Get Content Documents
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;
        Id conDocId2 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv2.Id].ContentDocumentId;
        Id conDocId3 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv3.Id].ContentDocumentId;
        
        List<ContentDocumentLink> cdlList = new List<ContentDocumentLink>();
        //Create ContentDocumentLink 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = job.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        cdlList.add(cdl);
        //Create ContentDocumentLink 
        ContentDocumentLink cdl2 = New ContentDocumentLink();
        cdl2.LinkedEntityId = job.Id;
        cdl2.ContentDocumentId = conDocId2;
        cdl2.shareType = 'V';
        cdlList.add(cdl2);
        //Create ContentDocumentLink 
        ContentDocumentLink cdl3 = New ContentDocumentLink();
        cdl3.LinkedEntityId = job1.Id;
        cdl3.ContentDocumentId = conDocId3;
        cdl3.shareType = 'V';
        cdlList.add(cdl3);
        
        Insert cdlList;
    }
    
}