metadatafullcopy/unpackaged/objects/Account_Roles__c.object
<CustomObject>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact ID</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Job_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Job ID</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Roles</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Roles Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <description>Job Project Site County-- used in Jitterbit mapping to sync with Timberline.</description>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Job Name field is used on New Job VF page, used to pass along to Timberline, and used to update Opportunity Name field via &apos;Opportunity Naming Convention&apos; workflow.</description>
        <label>Job Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advertising and Publications</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Building Consultant</fullName>
                </value>
                <value>
                    <fullName>Consulting Firm</fullName>
                </value>
                <value>
                    <fullName>Employee - Friends or Family Referral</fullName>
                </value>
                <value>
                    <fullName>Environmental Hygienist</fullName>
                </value>
                <value>
                    <fullName>Facilities Management/Building Engineer</fullName>
                </value>
                <value>
                    <fullName>General Contractor</fullName>
                </value>
                <value>
                    <fullName>Government or Municipality</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Independent Adjusting Company</fullName>
                </value>
                <value>
                    <fullName>Insurance Agent</fullName>
                </value>
                <value>
                    <fullName>Insurance Broker</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Live Chat</fullName>
                </value>
                <value>
                    <fullName>National Account (ERA, Contract, Etc)</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity Consumer Services</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity REO</fullName>
                </value>
                <value>
                    <fullName>Program - Alacrity Services</fullName>
                </value>
                <value>
                    <fullName>Program - American Emergency Services</fullName>
                </value>
                <value>
                    <fullName>Program - BrightServ</fullName>
                </value>
                <value>
                    <fullName>Program - CC Consumer Services</fullName>
                </value>
                <value>
                    <fullName>Program - Code Blue Network</fullName>
                </value>
                <value>
                    <fullName>Program - Contractor Connection</fullName>
                </value>
                <value>
                    <fullName>Program - Direct Assignment</fullName>
                </value>
                <value>
                    <fullName>Program - Direct Claims Management (DCMG)</fullName>
                </value>
                <value>
                    <fullName>Program - IMACC</fullName>
                </value>
                <value>
                    <fullName>Program - Innovation Property</fullName>
                </value>
                <value>
                    <fullName>Program - Lionsbridge</fullName>
                </value>
                <value>
                    <fullName>Program - NEXXUS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Office2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Office object to indicate what office the Job is taking place out of.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>ATIOffice2</relationshipLabel>
        <relationshipName>ATIOffice2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>Field to indicate the ATI office associated with the job.
(Hidden Field) Only for Apex Triggers Code and other reports not for UI.</description>
        <formula>Office2__r.Name</formula>
        <label>Office Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address__c</fullName>
        <description>Address of job project site</description>
        <label>Project Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <description>City of job project site</description>
        <label>Project Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <description>Project Site State</description>
        <label>Project Site State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Zipcode__c</fullName>
        <description>Project Site Zipcode</description>
        <label>Project Site Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Estimating/Review</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                </value>
                <value>
                    <fullName>Billing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Campaign_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Account_Roles__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Roles</label>
        <referenceTo>Account_Roles__c</referenceTo>
        <relationshipLabel>Campaign Junctions</relationshipLabel>
        <relationshipName>Campaign_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Junction</label>
    <nameField>
        <displayFormat>CJN-{0000}</displayFormat>
        <label>Campaign Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Flagstaff</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Anaheim</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Pittsburgh</fullName>
                </value>
                <value>
                    <fullName>Riverside</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>San Jose</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tuscon</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Office__c.object
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountRoleTriggerHandlerTest.cls
@isTest
Public Class AccountRoleTriggerHandlerTest{

@isTest
Static Void AccountTriggerFunctionalityTest(){

        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Restricted Process Execution' LIMIT 1];
        
        User usr = new User(LastName = 'Testofc',
                           FirstName='DeBki',
                           Alias = 'jliv',
                           Email = 'jason.liveston@asdf.com',
                           Username = 'testati@google.com',
                           ProfileId = profileId.id,
                           TimeZoneSidKey = 'GMT',
                           LanguageLocaleKey = 'en_US',
                           EmailEncodingKey = 'UTF-8',
                           LocaleSidKey = 'en_US'
                           );
                           
                           
        system.runAs(usr){
        
        Account acct = new Account (Name = 'Acme, Inc.');
        insert acct;

        Contact con = new Contact(
                          FirstName = 'Preludesys',
                          LastName = 'Test',
                          AccountId = acct.Id
                          );
        insert con;   
        
        
        Contact con1 = new Contact(
                          FirstName = 'Demand',
                          LastName = 'Blue',
                          AccountId = acct.Id
                          );
        insert con1;  
        
        Campaign camp = new Campaign(
                            Name = 'TestCampaign',
            				StartDate = system.today()-100,
                            EndDate = system.today()+10,
                            IsActive = TRUE
                            );            
        insert camp;
        
        
         Campaign camp1 = new Campaign(
                            Name = 'CampaignTest',
             				StartDate = system.today()-92,
                            EndDate = system.today()-90,
                            IsActive = TRUE
                            );            
        insert camp1;
        
        CampaignMember member = new CampaignMember(
            ContactId = con.Id,
            Status = 'sent',
            CampaignId = camp.Id
            ); 
        insert member; 
        
        
        CampaignMember member1 = new CampaignMember(
            ContactId = con1.Id,
            Status = 'sent',
            CampaignId = camp1.Id
            ); 
            
            
       Office__c office = new Office__c();
       office.Name = 'Office Test';
       insert office;
       
       ATI_Job__c job = new ATI_Job__c();
       job.name = 'Test';
       job.Job_Name__c = 'Job Test';
       job.Office2__c = office.id;
       job.Lead_Source__c = 'Advertising and Publications';
       job.Stage__c = 'Qualification';
       job.Project_Site_Address__c = '665 S 300 E';
       job.Project_Site_City__c = 'LasVegas';
       job.Project_Site_State__c = 'UT';
       job.Project_Site_Zipcode__c = '12345';
       job.County__c = 'CL';
       insert job;
       
       List<Account_Roles__c> accRoles = new List<Account_Roles__c>();
       List<Account_Roles__c> updAccRoles = new List<Account_Roles__c>();
       
       Account_Roles__c accRole = new Account_Roles__c();
       accRole.Contact_ID__c = con.id;
       accRole.Master_Job_ID__c = job.id;
       accRoles.add(accRole);
       
       Account_Roles__c accRole1 = new Account_Roles__c();
       accRole1.Contact_ID__c = con1.id;
       accRole1.Master_Job_ID__c = job.id;
       accRoles.add(accRole1);
       
       insert accRoles;
       
       for(Account_Roles__c acRole: accRoles){
       
       
           if(acRole.Contact_ID__c == con.Id){
           
               acRole.Contact_ID__c = con1.Id;
                updAccRoles.add(acRole);
           
           }
           
           else if(acRole.Contact_ID__c == con1.Id){
           
               acRole.Contact_ID__c = con.Id;
                updAccRoles.add(acRole);
           
           }
           
          
       
       
       }
       
  
       update updAccRoles;        
       delete updAccRoles;
       
       
     }         

  }
  
  @isTest
  Static Void AccountRoleFunctionalityBatchTest(){
  
  Account acct = new Account (Name = 'Acme, Inc.');
        insert acct;

        Contact con = new Contact(
                          FirstName = 'Preludesys',
                          LastName = 'Test',
                          AccountId = acct.Id
                          );
        insert con;   
        
        
        Contact con1 = new Contact(
                          FirstName = 'Demand',
                          LastName = 'Blue',
                          AccountId = acct.Id
                          );
        insert con1;  
        
        Campaign camp = new Campaign(
                            Name = 'TestCampaign',
                            EndDate = system.today()-100,
                            IsActive = TRUE
                            );            
        insert camp;
        
        
         Campaign camp1 = new Campaign(
                            Name = 'CampaignTest',
                            EndDate = system.today()-90,
                            IsActive = TRUE
                            );            
        insert camp1;
        
        CampaignMember member = new CampaignMember(
            ContactId = con.Id,
            Status = 'sent',
            CampaignId = camp.Id
            ); 
        insert member; 
        
        
        CampaignMember member1 = new CampaignMember(
            ContactId = con1.Id,
            Status = 'sent',
            CampaignId = camp1.Id
            ); 
            
       List<Account_Roles__c> accRolesBatch = new List<Account_Roles__c>();
       
       Account_Roles__c accRole2 = new Account_Roles__c();
       accRole2.Contact_ID__c = con.id;
       accRolesBatch.add(accRole2);
       
       Account_Roles__c accRole3 = new Account_Roles__c();
       accRole3.Contact_ID__c = con1.id;
       accRolesBatch.add(accRole3);

       insert accRolesBatch;
      List< Campaign_Junction__c> campJunctions = [select id from Campaign_Junction__c];
      delete campJunctions;
       
       Test.startTest();
       AccountRoleInsertBatch accRoleBatch = new AccountRoleInsertBatch();
       Database.ExecuteBatch(accRoleBatch);
       Test.stopTest();
       
       
       


}

}