metadatafullcopy/unpackaged/objects/Account_Roles__c.object
<CustomObject>
    <fields>
        <fullName>Master_Job_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Job ID</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Multiple_Roles__c</fullName>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary/Bill-to</fullName>
                </value>
                <value>
                    <fullName>Caller</fullName>
                </value>
                <value>
                    <fullName>Referred By</fullName>
                </value>
                <value>
                    <fullName>Project Site Contact</fullName>
                </value>
                <value>
                    <fullName>Property Owner</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Insurance Adjuster</fullName>
                </value>
                <value>
                    <fullName>Property/Facility Manager</fullName>
                </value>
                <value>
                    <fullName>HOA</fullName>
                </value>
                <value>
                    <fullName>Tenant</fullName>
                </value>
                <value>
                    <fullName>Insurance Agent/Broker</fullName>
                </value>
                <value>
                    <fullName>Independent Adjuster</fullName>
                </value>
                <value>
                    <fullName>Attorney/Risk Manager/Public Adjuster</fullName>
                </value>
                <value>
                    <fullName>Contractor/Consultant</fullName>
                </value>
                <value>
                    <fullName>Stakeholder</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Carrier Claims Adjuster</fullName>
                    <isActive>false</isActive>
                    <label>Carrier Claims Adjuster</label>
                </value>
                <value>
                    <fullName>General Contractor</fullName>
                    <isActive>false</isActive>
                    <label>General Contractor</label>
                </value>
                <value>
                    <fullName>Independent Claims Adjuster</fullName>
                    <isActive>false</isActive>
                    <label>Independent Claims Adjuster</label>
                </value>
                <value>
                    <fullName>Insurance Broker</fullName>
                    <isActive>false</isActive>
                    <label>Insurance Broker</label>
                </value>
                <value>
                    <fullName>Insurance carrier</fullName>
                    <isActive>false</isActive>
                    <label>Insurance carrier</label>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                    <isActive>false</isActive>
                    <label>Property Manager</label>
                </value>
                <value>
                    <fullName>Tenant Real Estimate / Facilities</fullName>
                    <isActive>false</isActive>
                    <label>Tenant Real Estimate / Facilities</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property ID</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles-old</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Property Owner</fullName>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                </value>
                <value>
                    <fullName>Tenant Real Estimate / Facilities</fullName>
                </value>
                <value>
                    <fullName>Independent Claims Adjuster</fullName>
                </value>
                <value>
                    <fullName>Carrier Claims Adjuster</fullName>
                </value>
                <value>
                    <fullName>General Contractor</fullName>
                </value>
                <value>
                    <fullName>Insurance carrier</fullName>
                </value>
                <value>
                    <fullName>Insurance Broker</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Bill To</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Roles</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Roles Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account does not exist or has been rejected.</errorMessage>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Rejected</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Rejected</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ATI Jobs</relationshipLabel>
        <relationshipName>ATI_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to link the primary Contact of the Job to the Opportunity</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Contact)</relationshipLabel>
        <relationshipName>ATIContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Adjuster_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Insurance Adjuster/Broker for this Job-- referenced in New Job VF page</description>
        <label>Insurance Adjuster/Broker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Insurance Adjuster/Broker)</relationshipLabel>
        <relationshipName>ATIJobIAB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Office object to indicate what office the Job is taking place out of.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>ATIOffice2</relationshipLabel>
        <relationshipName>ATIOffice2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Owner)</relationshipLabel>
        <relationshipName>ATIJobOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Contact_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field was created to contain information for Project Site Contacts that are Person Account (NOT Contact) records.</description>
        <label>Project Site Contact Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>ATISiteContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project Site Contact Name</description>
        <label>Project Site Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job (Project Site Contact Name)</relationshipLabel>
        <relationshipName>ProjectSiteContactName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property ID</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to link the primary Contact of the Job to the Opportunity</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Contact)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Adjuster_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Insurance Adjuster/Broker for this Job-- referenced in New Job VF page</description>
        <label>Insurance Adjuster/Broker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Insurance Adjuster/Broker)</relationshipLabel>
        <relationshipName>OpportunitiesIAB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Office object to indicate what office the Job is taking place out of.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Owner)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Contact_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field was created to contain information for Project Site Contacts that are Person Account (NOT Contact) records.</description>
        <label>Project Site Contact Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Site Contact Name</description>
        <label>Project Site Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Project Site Contact Name)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Create_Opportunity_Handler.cls
/**
* @File Name          : Create_Opportunity_Handler.cls
* @Description        : 
* @Author             : sean.gray@atirestoration.com
* @Group              : 
* @Last Modified By   : sean.gray@atirestoration.com
* @Last Modified On   : 3/18/2020, 7:35:16 AM
* @Modification Log   : 

* Ver       Date            	Author      		    			Modification
* 1.0    	3/18/2020   		sean.gray@atirestoration.com     	Initial Version
**/


//Create Opportunity when a job record is created
public without sharing class Create_Opportunity_Handler 
{
    public static void createOpportunity(ATI_Job__c[] listJobs)
    {
        system.debug('JobList is ' + listJobs);
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Job Opportunity').getRecordTypeId();
        List<Opportunity> listInsertOpportunity= new List<Opportunity>();
        List<Account_Roles__c> fetchBillToAccountRoles = new List<Account_Roles__c>();
        set<id> setJobsPropertyIds = new Set<id>();
        set<id> jobIds = new Set<id>();

        for(ATI_Job__c newJob: listJobs) {
            system.debug('Property Id is ' + newJob.Property_ID__c);
            if(newJob.Property_ID__c <> null) {
                setJobsPropertyIds.add(newJob.Property_ID__c) ; 
                jobIds.add(newjob.id);
                
            }
        }
        
        if(!jobIds.isEmpty()) {
        //     system.debug('Jobids ' + jobIds);
        //     fetchBillToAccountRoles = [select id,name, Multiple_Roles__c, Property_ID__c from Account_Roles__c where Master_Job_ID__c =: jobIds AND Multiple_Roles__c includes('Primary/Bill-to') LIMIT 1];  
        //     system.debug('Account Roles are ' + fetchBillToAccountRoles);
        //     //fetchBillToAccountRoles = [select id,name, Roles__c, Property_ID__c from Account_Roles__c where Property_ID__c IN: jobIds AND Multiple_Roles__c includes('Primary/Bill-to') LIMIT 1];  
        // }
        // system.debug('Account Roles are ' + fetchBillToAccountRoles);
        // if(!fetchBillToAccountRoles.isEmpty()){
            Opportunity newOpportunity = new Opportunity ();
            for(ATI_Job__c eachjob: listJobs) {
                newOpportunity.Job__c = eachjob.id;
                newOpportunity.RecordTypeId = recordTypeId;
                newOpportunity.StageName = 'Prospecting';
                //newOpportunity.Property__c = Fetch_BillTo_AccountRoles[0].Property_ID__c;
                newOpportunity.Property__c=eachjob.Property_ID__c;
                newOpportunity.Contact__c = eachjob.Contact__c;
                newOpportunity.Project_Site_Contact_Name__c = eachjob.Project_Site_Contact_Name__c;
                newOpportunity.Project_Site_Contact_Account__c = eachjob.Project_Site_Contact_Account__c;
                newOpportunity.Owner__c = eachjob.Owner__c;
                newOpportunity.Insurance_Adjuster_Broker__c = eachjob.Insurance_Adjuster_Broker__c;
                newOpportunity.Office2__c = eachjob.Office2__c;
                system.debug('Job Name is ' + eachjob.Name);
                newOpportunity.Name = eachjob.Name;
                system.debug('Job Name is ' + eachjob.Name);
                newOpportunity.Division__c = eachjob.Division__c;
                newOpportunity.Major_Event__c = eachjob.Major_Event__c;
                system.debug('Job Name is ' + eachjob.Name);
                newOpportunity.Job_Name__c= eachjob.Job_Name__c;
                newOpportunity.Project_Site_State__c= eachjob.Project_Site_State__c;
                newOpportunity.Project_Site_Address__c= eachjob.Project_Site_Address__c;
                newOpportunity.Project_Site_Zipcode__c= eachjob.Project_Site_Zipcode__c;
                newOpportunity.County__c=eachjob.County__c;
                newOpportunity.Project_Site_City__c= eachjob.Project_Site_City__c;
                newOpportunity.CloseDate = date.today();
                newOpportunity.AccountId = eachjob.Account__c;
                system.debug('Job Name is ' + eachjob.Name);
                if(eachjob.Referred_by__c <> null) {
                    newOpportunity.Contact__c=eachjob.Referred_by__c;
                } else {
                    newOpportunity.Contact__c=eachjob.Contact__c; 
                }
            }
            system.debug('Job Name is ');
            listInsertOpportunity.add(newOpportunity);
        }
       
        if(!listInsertOpportunity.isEmpty()){
            insert listInsertOpportunity;
        }
    }
    
    
    // Update opportunity record when Referred_by__c field is changed
    public static void updateOpportunity(ATI_Job__c[]  newJobsList,Map<id,ATI_Job__c> oldJobsList, Map<Id, ATI_Job__c> newJobMap){
        Map<Id,Opportunity> OppMap =new Map<Id,Opportunity>();
        Boolean Changed = false;
        set<id> setJobIds = new Set<id>();
        
        for(ATI_Job__c newJob: newJobsList) {
            if(newJob.Property_ID__c <> null) {
                setJobIds.add(newJob.Id) ; 
            }
        }
        if(!setJobIds.isEmpty()){
            system.debug('Number of job ids' + setJobIds);
            List<Opportunity> Opp = [Select Id, Job__c from Opportunity where Job__c =:setJobIds];
            if(!Opp.isEmpty())
            {
                for(Opportunity o: opp)
                {
                    OppMap.put(o.Id, o);
                }
            }
        // ID OpportunityID = (ID) [Select ID from Opportunity where Job__c =:setJobIds Limit 1].ID;
        system.debug('Number of Opps ' + Opp);
        if(!OppMap.isEmpty()){
        for(Id o:OppMap.keyset()){
            Opportunity oppInLoop = OppMap.get(o);
            ATI_Job__c jobInOpp = newJobMap.get(oppInLoop.Job__c);
             
            if(oldJobsList.containsKey(jobInOpp.Id)){
                ATI_Job__c jobRecord = oldJobsList.get(jobInOpp.id);
                if(jobRecord.Referred_by__c <> jobInOpp.Referred_by__c || jobRecord.Name != jobInOpp.Name || jobRecord.Division__c != jobInOpp.Division__c
                || jobRecord.Amount__c != jobInOpp.Amount__c || jobRecord.Office2__c != jobInOpp.Office2__c){
                    OppMap.get(o).Division__c = jobInOpp.Division__c;
                    OppMap.get(o).Office2__c = jobInOpp.Office2__c;
                    OppMap.get(o).Amount = jobInOpp.Amount__c;
                    OppMap.get(o).Name = jobInOpp.Name;
                    Changed = true;
                    if(jobInOpp.Referred_by__c <> null){
                        OppMap.get(o).Contact__c=jobInOpp.Referred_by__c;
                    } else {
                        OppMap.get(o).Contact__c=jobInOpp.Contact__c;                           
                    }
                }                   
            }
        }
    }
}
        
        if(Changed)
        {
            update OppMap.values();
        }
    }
}