metadatafullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Unapproved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Branch_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up field to note the Branch Manager that will need to assign a PM to the job.</description>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobBM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to link the primary Contact of the Job to the Opportunity</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jobs (Contact)</relationshipLabel>
        <relationshipName>ATIContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Adjuster_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Insurance Adjuster/Broker for this Job-- referenced in New Job VF page</description>
        <label>Insurance Adjuster/Broker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Insurance Adjuster/Broker)</relationshipLabel>
        <relationshipName>ATIJobIAB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Job Name field is used on New Job VF page, used to pass along to Timberline, and used to update Opportunity Name field via &apos;Opportunity Naming Convention&apos; workflow.</description>
        <label>Job Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Job</label>
        <referenceTo>Master_Job__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Office object to indicate what office the Job is taking place out of.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>ATIOffice2</relationshipLabel>
        <relationshipName>ATIOffice2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>Field to indicate the ATI office associated with the job.
(Hidden Field) Only for Apex Triggers Code and other reports not for UI.</description>
        <formula>Office2__r.Name</formula>
        <label>Office Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Account__c</fullName>
        <description>Primary Account of Job-- referenced in New Job VF page</description>
        <label>Primary Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Caller Account</fullName>
                </value>
                <value>
                    <fullName>Project Site Contact</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Site_Address_2__c</fullName>
        <label>Project Site Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address__c</fullName>
        <description>Address of job project site</description>
        <label>Project Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <description>City of job project site</description>
        <label>Project Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Contact_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field was created to contain information for Project Site Contacts that are Person Account (NOT Contact) records.</description>
        <label>Project Site Contact Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>ATISiteContact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Contact_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project Site Contact Name</description>
        <label>Project Site Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job (Project Site Contact Name)</relationshipLabel>
        <relationshipName>ProjectSiteContactName</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Record_Id__c</fullName>
        <externalId>true</externalId>
        <label>Project Site Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <description>Project Site State</description>
        <label>Project Site State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Zipcode__c</fullName>
        <description>Project Site Zipcode</description>
        <label>Project Site Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property ID</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <label>Office</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Flagstaff</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Anaheim</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Pittsburgh</fullName>
                </value>
                <value>
                    <fullName>Riverside</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>San Francisco</fullName>
                </value>
                <value>
                    <fullName>San Jose</fullName>
                </value>
                <value>
                    <fullName>Seattle</fullName>
                </value>
                <value>
                    <fullName>Tuscon</fullName>
                </value>
                <value>
                    <fullName>Tampa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Master_Job__c.object
<CustomObject>
    <fields>
        <fullName>Branch_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Master_Jobs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Office2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>Master Jobs</relationshipLabel>
        <relationshipName>Master_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address_2__c</fullName>
        <label>Project Site Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address__c</fullName>
        <label>Project Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <formula>Property__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <formula>Property__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site State</label>
        <type>Text</type>
    </fields>
    <label>Master Job</label>
    <nameField>
        <label>Master Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Office__c.object
<CustomObject>
    <fields>
        <fullName>Asbestos_Operations_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asbestos Operations Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>OfficesdlDu</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>General Branch Manager of office, if no divisions are applicable.</description>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Offices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewJobController_Test.cls
@isTest
private class NewJobController_Test {
    static testmethod void NewJobController_Test() {
        Id u2 = UserInfo.getUserId();
        
        system.runAs(new User(Id=Userinfo.getUserId())){
            
            Map <String, Schema.RecordTypeInfo> jobRecordTypeMap = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName;
            Id notApprovedId = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName.get('New Job (Not Approved)').RecordTypeId;
            Id approvedId = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName.get('Job (Approved)').RecordTypeId;
    
            TestDataUtil.createCustomSettings_TriggerStatus();
            //create Account 
            Office__c off = new Office__c(Name = 'HQ');
            insert off;
            list<Account> lstAccounts = TestDataUtil.createAccounts(2, false, new map<String,Object>());
            lstAccounts[0].type ='Property Owner';             
            insert lstAccounts;
            
            lstAccounts[0].Status__c = 'Approved';
            update lstAccounts;
            
            list<contact> lstContact = TestDataUtil.createContacts(2, false, new map<String,Object>(), lstAccounts[0].Id);
            insert lstContact;
            List<ATI_Job__c> jobs = new List<ATI_Job__c>();
            Jobs = TestDataUtil.createJob(1, false, new map<String,Object>(), lstAccounts[0].Id);
    
            Jobs[0].contact__c = lstContact[0].id;
            Jobs[0].Project_Site_Contact_Name__c = lstContact[1].id;
            Jobs[0].Insurance_Adjuster_Broker__c = lstContact[0].id;
            Jobs[0].Primary_Account__c = 'Caller Account';
            Jobs[0].Project_Site_Address__c = '7550 st. patrick way';
            Jobs[0].Project_Site_Address_2__c = '';
            Jobs[0].Project_Site_City__c = 'Dublin';
            Jobs[0].Project_Site_State__c = 'CA';
            Jobs[0].Project_Site_Zipcode__c = '94568';
            Jobs[0].Project_Site_Contact_Account__c = lstAccounts[0].id;
            Jobs[0].Project_Site_Record_Id__c = '12345';
            Jobs[0].RecordTypeId = notApprovedId;
            Jobs[0].Job_Name__c ='test';
            
    
        
            
            insert Jobs;  
            NewJobController.GetUserInfoAndIntakeStatus(jobs[0].id); 
            NewJobController.GetProperties('Test');
            NewJobController.GetOffices('HQ');
            NewJobController.CheckId(jobs[0].Property_Id__c);
           
            NewJobController.CheckId6(jobs[0].Property_Id__c);
            
            NewJobController.GetPropertyInfo('Whittier','15632 Youngwood Drive', 'CA', '90603');
            NewJobController.GetJobInfo(jobs[0].id);
            NewJobController.GetMajorEvents('Test');

            NewJobController.InsertContact('FirstName', 'LastName', 'test@gmail.com', '222-222-2222', 'Adjuster', '', '15632 Youngwood Drive', 'Whittier', 'CA', '90603', 'US', lstAccounts[0].Id, false);
            NewJobController.InsertAccount('Name',  '222-222-2222' , 'Farmers', '', '15632 Youngwood Drive', 'Whittier', 'CA', '90603', 'US');
            // NewJobController.GetAccountRoless(jobs[0].Property_Id__c);
            NewJobController.InsertPersonAccount('Name', 'LastName', '222-222-2222' , 's@gmail.com','Farmers', '', '15632 Youngwood Drive', 'Whittier', 'CA', '90603', 'US');
            // NewJobController.GetCustomers('Test');
            // NewJobController.GetDivisionPicklist();
            // NewJobController.GetDivisionPicklist1();
            // NewJobController.GetDivisionPicklist2();
            // NewJobController.GetDivisionPicklist3();
            
           
            // NewJobController.GetEsJobTypePicklist();
            // NewJobController.GetLeadSourcePicklist();
            // NewJobController.GetMultipleDivisionPicklist();
            // NewJobController.GetPropertyTypePicklist();
            // NewJobController.GetJobClassPicklist();
            // NewJobController.GetJobClassPicklist1();
            // NewJobController.GetJobClassPicklist2();
            // NewJobController.GetJobClassPicklist3();
            // NewJobController.GetJobClassPicklist4();
            // NewJobController.GetContactAccounts('Test');
            // NewJobController.getPickListValuesIntoList();
            // NewJobController.GetUserName();
            // NewJobController.GetUsers('Sean');
            // NewJobController.GetCustomers('Test');
            // NewJobController.GetUserInfo();
            NewJobController.AfterHoursJobCreation('TestJob', 'Construction', '', off.id, '15632 Youngwood Drive', 'CA', 'Whittier', '90603', 'US', '15632 Youngwood Drive', 'Test', 'Test', '', '');
            String AccountRoleInfo = '{"AccountRoleLineItems":[{"Text":"Primary/Bill-to;Caller;Referred By;Project Site Contact","Contact":"' + lstContact[0].Id + '","Account":"' + lstAccounts[0].Id + '"}]}';
            String PropertyInfo = '{"PropertyId":"","City":"El Monte","Country":"United States","State":"CA","Street":"3534 North Peck Road","Zip":"91731","AddressLine2":"444","AlternateName":"test23"}';
            String JobInfo = '{"Description":"Type of Loss","JobRealName":"","Division":"Catastrophes","Office":"' + off.Id + '","JobClass":"Educational - Private","ProjectDirector":"' + u2 + '","TakenBy":"' + u2 + '","Claim":"444","Policy":"444","JobName":"test job RQF x232","LeadSource":"Consulting Firm","MultipleDivisions":"Asbestos","DateOfLoss":"2020-05-07","ClientJob":"44","YearBuilt":"1999","MajorEvent":""}';
            // NewJobController.CreateNewJob(AccountRoleInfo, PropertyInfo, JobInfo, '', 'AfterHoursJobEntry', '', true);
            NewJobController.CreateNewJob(AccountRoleInfo, PropertyInfo, JobInfo, '', 'AfterHoursJobEntry', '', false);
            NewJobController.CreateNewJob(AccountRoleInfo, PropertyInfo, JobInfo, '', 'NewJobEntry', '', false);
            // NewJobController.CreateNewJob(AccountRoleInfo, PropertyInfo, JobInfo, '', 'AfterHoursJobEntry', '');
            // NewJobController.CreateNewProp(AccountRoleInfo, PropertyInfo);
            // NewJobController.UpdateProperty(jobs[0].Property_Id__c, '15632 Youngwood Drive', 'Whittier', 'CA', '90603','USA');
        }
        
    }
    static testmethod void NewJobController_Test1() {
        Id u2 = UserInfo.getUserId();
        
        system.runAs(new User(Id=Userinfo.getUserId())){
            Map <String, Schema.RecordTypeInfo> jobRecordTypeMap = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName;
            Id notApprovedId = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName.get('New Job (Not Approved)').RecordTypeId;
            Id approvedId = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName.get('Job (Approved)').RecordTypeId;
    
            TestDataUtil.createCustomSettings_TriggerStatus();
            //create Account 
            Office__c off = new Office__c(Name = 'HQ');
            insert off;
            list<Account> lstAccounts = TestDataUtil.createAccounts(2, false, new map<String,Object>());
            lstAccounts[0].type ='Property Owner';             
            insert lstAccounts;
            
            lstAccounts[0].Status__c = 'Approved';
            update lstAccounts;
            
            list<contact> lstContact = TestDataUtil.createContacts(2, false, new map<String,Object>(), lstAccounts[0].Id);
            insert lstContact;
            List<ATI_Job__c> jobs = new List<ATI_Job__c>();
            Jobs = TestDataUtil.createJob(1, false, new map<String,Object>(), lstAccounts[0].Id);
    
            Jobs[0].contact__c = lstContact[0].id;
            Jobs[0].Project_Site_Contact_Name__c = lstContact[1].id;
            Jobs[0].Insurance_Adjuster_Broker__c = lstContact[0].id;
            Jobs[0].Primary_Account__c = 'Caller Account';
            Jobs[0].Project_Site_Address__c = '7550 st. patrick way';
            Jobs[0].Project_Site_Address_2__c = '';
            Jobs[0].Project_Site_City__c = 'Dublin';
            Jobs[0].Project_Site_State__c = 'CA';
            Jobs[0].Project_Site_Zipcode__c = '94568';
            Jobs[0].Project_Site_Contact_Account__c = lstAccounts[0].id;
            Jobs[0].Project_Site_Record_Id__c = '12345';
            //Jobs[0].RecordTypeId = notApprovedId;
            Jobs[0].Job_Name__c ='test';
            
    
        
            
            insert Jobs;   
            NewJobController.GetProperties('Test');
            NewJobController.GetOffices('HQ');
            NewJobController.CheckId(jobs[0].Property_Id__c);
           
            NewJobController.CheckId6(jobs[0].Property_Id__c);
            
            NewJobController.GetPropertyInfo('Whittier','15632 Youngwood Drive', 'CA', '90603');
            NewJobController.GetJobInfo(jobs[0].id);
            NewJobController.GetMajorEvents('Test');

            NewJobController.InsertContact('FirstName', 'LastName', 'test@gmail.com', '222-222-2222', 'Adjuster', '', '15632 Youngwood Drive', 'Whittier', 'CA', '90603', 'US', lstAccounts[0].Id, false);
            NewJobController.InsertAccount('Name',  '222-222-2222' , 'Farmers', '', '15632 Youngwood Drive', 'Whittier', 'CA', '90603', 'US');
            // NewJobController.GetAccountRoless(jobs[0].Property_Id__c);
            NewJobController.InsertPersonAccount('Name', 'LastName', '222-222-2222' , 's@gmail.com','Farmers', '', '15632 Youngwood Drive', 'Whittier', 'CA', '90603', 'US');
            NewJobController.GetCustomers('Test');
            NewJobController.GetDivisionPicklist();
            NewJobController.GetDivisionPicklist1();
            NewJobController.GetDivisionPicklist2();
            NewJobController.GetDivisionPicklist3();
            
            JobTriggerHandlerWorkflow.CheckId6(jobs[0].Property_Id__c);
            NewJobController.GetEsJobTypePicklist();
            NewJobController.GetLeadSourcePicklist();
            NewJobController.GetMultipleDivisionPicklist();
            NewJobController.GetPropertyTypePicklist();
            NewJobController.GetJobClassPicklist();
            NewJobController.GetJobClassPicklist1();
            NewJobController.GetJobClassPicklist2();
            NewJobController.GetJobClassPicklist3();
            NewJobController.GetJobClassPicklist4();
            NewJobController.GetContactAccounts('Test');
            NewJobController.getPickListValuesIntoList();
            NewJobController.GetUserName();
            NewJobController.GetUsers('Sean');
            NewJobController.GetCustomers('Test');
            NewJobController.GetUserInfo();
            SubmitForApprovalExtension.submitForApproval(jobs[0].Master_Job__c);
            SubmitForApprovalExtension.submitForApproval(lstContact[0].Id);
            String AccountRoleInfo = '{"AccountRoleLineItems":[{"Text":"Primary/Bill-to;Caller;Referred By;Project Site Contact","Contact":"' + lstContact[0].Id + '","Account":"' + lstAccounts[0].Id + '"}]}';
            String PropertyInfo = '{"PropertyId":"","City":"El Monte","Country":"United States","State":"CA","Street":"3534 North Peck Road","Zip":"91731","AddressLine2":"444","AlternateName":"test23"}';
            String JobInfo = '{"Description":"Type of Loss","JobRealName":"","Division":"Catastrophes","Office":"' + off.Id + '","JobClass":"Educational - Private","ProjectDirector":"' + u2 + '","TakenBy":"' + u2 + '","Claim":"444","Policy":"444","JobName":"test job RQF x232","LeadSource":"Consulting Firm","MultipleDivisions":"Asbestos","DateOfLoss":"2020-05-07","ClientJob":"44","YearBuilt":"1999","MajorEvent":""}';
            NewJobController.CreateNewJob(AccountRoleInfo, PropertyInfo, JobInfo, '', 'AfterHoursJobEntry', '', true);
            NewJobController.CreateNewJob(AccountRoleInfo, PropertyInfo, JobInfo, jobs[0].Master_Job__c, 'NewJobEntry', '', true);
            NewJobController.CreateNewJob(AccountRoleInfo, PropertyInfo, JobInfo, jobs[0].Master_Job__c, 'AfterHoursJobEntry', '', false);
            
            NewJobController.CreateNewProp(AccountRoleInfo, PropertyInfo);
            NewJobController.UpdateProperty(jobs[0].Property_Id__c, '15632 Youngwood Drive', 'Whittier', 'CA', '90603','USA');
        }
    }
    static testmethod void NewJobController_Test2() {
        Id u2 = UserInfo.getUserId();
        
        system.runAs(new User(Id=Userinfo.getUserId())){
            Map <String, Schema.RecordTypeInfo> jobRecordTypeMap = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName;
            Id notApprovedId = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName.get('New Job (Not Approved)').RecordTypeId;
            Id approvedId = Schema.SObjectType.ATI_job__c.RecordTypeInfosByName.get('Job (Approved)').RecordTypeId;
            Integer NumToInsert = 15;
            
            ObjectInserts ObjectData = TestDataUtil.createObjects(NumToInsert, false);
            Office__c off = new Office__c(Name = 'Anaheim', Branch_Manager__c = u2, Asbestos_Operations_Manager__c = u2);
            insert off;
            List<ATI_Job__c> jobs = ObjectData.jobList;
            jobs[0].RecordTypeId = notApprovedId;
            jobs[1].RecordTypeId = approvedId;
            
            jobs[13].Office2__c = off.Id;
            jobs[13].Division__c = 'Lead';
            jobs[14].Office2__c = off.Id;
            jobs[14].Division__c = 'Catastrophes';
            insert jobs;
            TestDataUtil.CreateObjectAccountRoles(NumToInsert, jobs, ObjectData.accountList, ObjectData.contactList);
            ATI_Job__c job = jobs[0];
            ATI_Job__c job1 = jobs[2];
            ATI_Job__c job5 = jobs[5];
            
            Account [] acct= ObjectData.accountList;
            Contact [] cont = ObjectData.contactList;
            Master_Job__c [] masterjob = ObjectData.masterjobList;
            Office__c [] offices = ObjectData.OfficeList;
            User [] users = ObjectData.UserList;
            Property__c [] property = ObjectData.PropertyList;
            
            job.RecordTypeId = approvedId;
            job.Stage__c = 'Won';
            job.Office2__c = offices[0].Id;
            job.Project_Manager_New__c = u2;
            job.Project_Manager__c = users[2].Id;
            job.Amount__c = 100;
            job.Division__c = 'Biohazard';

            job1.Master_Job__c = masterjob[4].Id;
            
            job1.Office2__c = offices[0].Id;
            job1.Division__c = 'Microbial';
            job1.Project_Manager_New__c = u2;
            job1.Project_Manager__c = users[2].Id;
            job1.Account_Executive_1__c = users[2].Id;
            job1.Account_Executive_2__c = users[3].Id;
            job1.Branch_Manager__c = users[4].Id;
            job5.Division__c = 'Catastrophes';
            List<ATI_Job__c> jobsToUpdate = new List<ATI_Job__c>();
            jobsToUpdate.add(job);
            jobsToUpdate.add(job1);
            jobsToUpdate.add(job5);
            
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new fake_AddTask());
            update jobsToUpdate;
            Test.stopTest();
            // Test.startTest();
            // Test.setMock(HttpCalloutMock.class, new MockHttpGoogleMapsResponse());
            // NewJobController.CreateNewJob(AccountRoleInfo, PropertyInfo, JobInfo, MasterJobId, JobEntryType, jobrecordId, ExistingMasterJob);
            // Test.stopTest();
            
        }
    }
    public class fake_AddTask implements HttpCalloutMock{
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Create a fake response
            string response = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'+
                '<soapenv:Body>'+
                '<ns1:addTaskForManagerResponse soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns1="http://nads.econz.co.nz/timecard1/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">'+
                '<addTaskForManagerResponse xsi:type="ns1:AddNewTaskResult" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://nads.econz.co.nz/timecard1/">'+
                '<accessDeniedFailure xsi:type="ns2:AccessDeniedFailure" xsi:nil="true" xmlns:ns2="http://auth.soap.econz.co.nz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />'+
                '<validationFailure xsi:type="ns3:ValidationFailure" xsi:nil="true" xmlns:ns3="http://soap.econz.co.nz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />'+
                '</addTaskForManagerResponse>'+
                '</ns1:addTaskForManagerResponse>'+
                '</soapenv:Body>'+
                '</soapenv:Envelope>';
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody(response);
            res.setStatusCode(200);
            return res;
        }
    }
    // public class ObjectData {
    //     public list<ATI_Job__c> jobList {get;set;}
    //     public list<Contact> contactList {get;set;}
    //     public list<Account> accountList {get;set;}
    //     public list<Master_Job__c> masterjobList {get;set;}
    //     public list<Property__c> propertyList {get;set;}
    // }
}