metadatafullcopy/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Create_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Billing_Address__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Addresses</relationshipLabel>
        <relationshipName>Billing_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Zipcode__c</fullName>
        <label>Billing Zipcode</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Billing Address</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Billing Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Courtesy_Call_Outcome__c</fullName>
        <label>Courtesy Call Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Disputed Invoice</fullName>
                </value>
                <value>
                    <fullName>Left Message</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Sent Copy of Invoice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountTriggerUtility.cls
public without sharing class AccountTriggerUtility {
    // helper method to be called on After Insert of accounts.
    public static void afterAccountInsert( List<Account> accounts ){
        createBillingAddressRecords( null, accounts );
    }
    
    public static void afterAccountUpdate( Map<Id, Account> oldAccountsMap, List<Account> newAccounts ){    
        createBillingAddressRecords( oldAccountsMap, newAccounts );
    }
    
    private static void createBillingAddressRecords( Map<Id, Account> oldAccountsMap, List<Account> accounts ){
        List<Billing_Address__c> billingAddresses = new List<Billing_Address__c>();
        for( Account acc : accounts ){
            Account oldAcc = oldAccountsMap == null ? null : oldAccountsMap.get( acc.Id );
            if((oldAcc == null && ( acc.BillingCity != null || acc.BillingState != null ||
                    acc.BillingCountry != null || acc.BillingCountry != null || acc.BillingPostalCode != null))|| 
                (oldAcc != null && oldAcc.Create_Billing_Address__c != acc.Create_Billing_Address__c && acc.Create_Billing_Address__c)) {
                Billing_Address__c ba = new Billing_Address__c();
                ba.Account__c = acc.Id;
                system.debug(acc.billingStreet);
                ba.Billing_City__c = acc.BillingCity;
                ba.Billing_State__c = acc.BillingState;
                ba.Billing_Street__c = acc.BillingStreet;
                ba.Billing_Country__c = acc.BillingCountry;
                    system.debug( acc.BillingPostalCode);
                ba.Billing_Zipcode__c = acc.BillingPostalCode;
                billingAddresses.add( ba );
            }
        }
        if( !billingAddresses.isEmpty() ){
            insert billingAddresses;
        }
    }

    public static void UpdateRelatedCases(string recordId, string Notes, string CourtesyCallOutcome)
    {
        List<Case> cases = [Select Id, Status, Courtesy_Call_Outcome__c FROM Case WHere AccountId =: recordId];
        if(!cases.isEmpty())
        {
            for(Case c : cases)
            {
                c.Courtesy_Call_Outcome__c = CourtesyCallOutcome;
                
                //related case criteria, they must have status = invoiced
                //Update Milestone status? trigger completion of courtesy call followup in each related case, add note TASK to each case and account

            }
            update cases;
        }
    }
}