metadatafullcopy/unpackaged/objects/Account_Roles__c.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account ID</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact ID</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Job_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Job ID</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Account Roles</relationshipLabel>
        <relationshipName>Account_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Multiple_Roles__c</fullName>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Primary/Bill-to</fullName>
                </value>
                <value>
                    <fullName>Caller</fullName>
                </value>
                <value>
                    <fullName>Referred By</fullName>
                </value>
                <value>
                    <fullName>Project Site Contact</fullName>
                </value>
                <value>
                    <fullName>Property Owner</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Insurance Adjuster</fullName>
                </value>
                <value>
                    <fullName>Property/Facility Manager</fullName>
                </value>
                <value>
                    <fullName>HOA</fullName>
                </value>
                <value>
                    <fullName>Tenant</fullName>
                </value>
                <value>
                    <fullName>Insurance Agent/Broker</fullName>
                </value>
                <value>
                    <fullName>Independent Adjuster</fullName>
                </value>
                <value>
                    <fullName>Attorney/Risk Manager/Public Adjuster</fullName>
                </value>
                <value>
                    <fullName>Contractor/Consultant</fullName>
                </value>
                <value>
                    <fullName>Stakeholder</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Legacy</fullName>
                </value>
                <value>
                    <fullName>Carrier Claims Adjuster</fullName>
                    <isActive>false</isActive>
                    <label>Carrier Claims Adjuster</label>
                </value>
                <value>
                    <fullName>General Contractor</fullName>
                    <isActive>false</isActive>
                    <label>General Contractor</label>
                </value>
                <value>
                    <fullName>Independent Claims Adjuster</fullName>
                    <isActive>false</isActive>
                    <label>Independent Claims Adjuster</label>
                </value>
                <value>
                    <fullName>Insurance Broker</fullName>
                    <isActive>false</isActive>
                    <label>Insurance Broker</label>
                </value>
                <value>
                    <fullName>Insurance carrier</fullName>
                    <isActive>false</isActive>
                    <label>Insurance carrier</label>
                </value>
                <value>
                    <fullName>Property Manager</fullName>
                    <isActive>false</isActive>
                    <label>Property Manager</label>
                </value>
                <value>
                    <fullName>Tenant Real Estimate / Facilities</fullName>
                    <isActive>false</isActive>
                    <label>Tenant Real Estimate / Facilities</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Roles</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Account Roles Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Insurance_Adjuster_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Insurance Adjuster/Broker for this Job-- referenced in New Job VF page</description>
        <label>Insurance Adjuster/Broker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Insurance Adjuster/Broker)</relationshipLabel>
        <relationshipName>ATIJobIAB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Insurance Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs (Insurance Company)</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchForJobs.cls
global class BatchForJobs implements Database.Batchable<sObject> {
    global String Query;
    global final String Entity;
    global final String Field;
    global final String Value;
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<ATI_Job__c> scope)
    {
        Map<Id,ATI_Job__c> jobMap = new Map<Id,ATI_Job__c>();
        Map<Id,ATI_Job__c> jobMapUpdate = new Map<Id,ATI_Job__c>();
        jobMap.putall(scope);
        Map<Id, Account_Roles__c> accountRoleMap = 
        new Map<Id,Account_Roles__c>([Select Id, Account_Id__c, Contact_Id__c, Master_Job_ID__c, Multiple_Roles__c
                                    FROM Account_Roles__c
                                    Where Master_Job_ID__c =:jobMap.keyset() AND Multiple_Roles__c INCLUDES ('Insurance Adjuster/Company')]);

        for(Account_Roles__c a : accountRoleMap.values())
        {
            ATI_Job__c job = new ATI_Job__c(Id = a.Master_Job_Id__c, Insurance_Company__c = a.Account_Id__c, Insurance_Adjuster_Broker__c = a.Contact_Id__c);
            jobMapUpdate.put(job.Id, job);
        }
        
        update jobMapUpdate.values();
        
    }
            
        global void finish(Database.BatchableContext BC){
        }
        }