metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Created</fullName>
                    <default>true</default>
                    <label>Not Created</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <description>This date should reflect the estimated completion date on the contract with the customer.</description>
        <label>Estimated Completion Date per Contract</label>
        <type>Date</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>ATI_Job__c</fullName>
        <label>Job</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Allocations__c</fullName>
        <label>Allocations (%)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <default>true</default>
                    <label>0</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BlankValue__c</fullName>
        <label>BlankValue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0/0</fullName>
                    <default>true</default>
                    <label>0/0</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <formula>ATI_Job__r.Estimated_Completion_Date__c</formula>
        <inlineHelpText>To edit the date, please refer back to ATI Job.</inlineHelpText>
        <label>Estimated Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Profit__c</fullName>
        <description>Revenue * 10% if the 10/10 is checked. Calculated via code.</description>
        <label>Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <formula>ATI_Job__r.Job_Start_Date__c</formula>
        <inlineHelpText>To edit the date, please refer back to ATI Job.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Type__c</fullName>
        <description>For XactAnalysis estimate import to budget</description>
        <label>Activity Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Actual_Costs_BL__c</fullName>
        <description>For XactAnalysis estimate import to budget</description>
        <label>Actual Costs BL</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Costs__c</fullName>
        <formula>IF(AND(Subcontractor_bid__c = 0,  In_House_Total__c  = 0,  Materials__c = 0), Subcontractor_bid__c  +  In_House_Total__c  +  Materials__c, Subcontractor_bid__c  +  In_House_Total__c  +  Materials__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Actual Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocation_Amount__c</fullName>
        <description>This will bring the value of allocation formula so we can use it on Subtotal Rollup summary.</description>
        <label>Allocation Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocations__c</fullName>
        <formula>Revenue__c  *  VALUE(TEXT(Budget__r.Allocations__c)) / 100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Allocations</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Goal_Amount__c</fullName>
        <description>This will bring the value of budget goal formula so we can use it on Rollup summary.</description>
        <label>Budget Goal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Goal__c</fullName>
        <description>Revenue minus selected budget goal, minus selected allocations, minus selected program fees, plus 20% if using 10/10 allocations</description>
        <formula>Revenue__c - 

(Revenue__c*(VALUE(TEXT( GP__c))/100)) - 

(Revenue__c*(VALUE(TEXT(Budget__r.Allocations__c))/100)) - 

(Revenue__c*(VALUE(TEXT(Budget__r.X3_Program_Fees__c))/100)) + 



(IF(X10_10_Allocation__c == true, 0.2*(Revenue__c - 

(Revenue__c*(VALUE(TEXT( GP__c))/100)) - 

(Revenue__c*(VALUE(TEXT(Budget__r.Allocations__c))/100)) - 

(Revenue__c*(VALUE(TEXT(Budget__r.X3_Program_Fees__c))/100))), 

0) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Budget Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Budget Line Items</relationshipLabel>
        <relationshipName>Budget_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Burden__c</fullName>
        <formula>(In_House_Rate__c  * 0.2)  *  In_House_Hours__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Burden</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <label>Estimated Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fees__c</fullName>
        <label>Fees</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Profit__c</fullName>
        <formula>Profit__c  /  Revenue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>In_House_Hours__c</fullName>
        <label>In-House Hours</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_House_Rate__c</fullName>
        <label>In-House Rate</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>In_House_Total__c</fullName>
        <formula>(In_House_Hours__c  *  In_House_Rate__c  ) + Burden__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>In-House Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Item Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Materials__c</fullName>
        <label>Materials</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Costs_BL__c</fullName>
        <description>For XactAnalysis estimate import to budget</description>
        <label>Other Costs BL</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Costs__c</fullName>
        <label>Other Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Profit__c</fullName>
        <formula>Revenue__c  -  Actual_Costs__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Profit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_Fees__c</fullName>
        <formula>Revenue__c * VALUE(TEXT(Budget__r.X3_Program_Fees__c )) / 100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Selector__c</fullName>
        <label>Selector</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subcontractor__c</fullName>
        <label>Subcontractor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcontractor_bid__c</fullName>
        <label>Subcontractor bid</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X10_10_Allocation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>10% overhead and 10% profit.</description>
        <label>10/10 Allocation</label>
        <type>Checkbox</type>
    </fields>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{YYYY}{MM}{DD}-{00}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Budget_Line_Item__c/fields/In_House_Rate_Full__c.field-meta.xml
<CustomField>
    <fullName>In_House_Rate_Full__c</fullName>
    <label>In-House Rate Full</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BudgetCloneController.cls
public class BudgetCloneController {

    public Budget__c BudgetRecord;
    public String job{get;set;}
    ApexPages.StandardController ExtCon;
  
    public BudgetCloneController(ApexPages.StandardController controller) {
         this.ExtCon = controller;
         BudgetRecord = (Budget__c)controller.getRecord();        
         job = BudgetRecord.ATI_Job__c;          
    }

    public void cloneLineItem(ID budgetId, ID oldBudget){

         System.debug('this is inside the clone method');
        // copy over the line items - ONLY INCLUDE THE FIELDS YOU WANT TO CLONE
         List<Budget_Line_Item__c> items = new List<Budget_Line_Item__c>();
         
         integer count = 0;
         
         //Query the old lineitems
         //clone each line item
         //assign them the new ID
         //add them to the list
         for (Budget_Line_Item__c LI : [Select Id, Name, Actual_Costs__c, Allocations__c, Budget__c, Burden__c, Program_Fees__c, Estimated_Completion_Date__c, Gross_Profit__c, 
                                        In_House_Hours__c, In_House_Rate__c, In_House_Rate_Full__c, In_House_Total__c, Materials__c, Profit__c, Revenue__c, Start_Date__c, 
                                        Budget_Goal__c, Budget_Goal_Amount__c, Subcontractor__c, Subcontractor_bid__c, Item_Description__c, Other_Costs__c,Other_Costs_BL__c,Selector__c,
                                        X10_10_Allocation__c, Activity_Type__c, Actual_Costs_BL__c, Allocation_Amount__c, BlankValue__c,Equipment__c,
                                        Fees__c, Program_Fee_Amount__c, Quantity__c,
                                        Trade__c, Trade_Option__c, OrderNumber__c, GP__c,In_House_Hours_BL__c,In_House_Rate_BL__c,In_House_Total_BL__c,
                                        From_Xact__c, is_Parent__c, Bypass_Calculation__c, DonotDelete__c, Equipment_BL__c,Is_sub_Parent__c, Materials_BL__c, Unit__c
                                        FROM Budget_Line_Item__c WHERE Budget__c = :oldBudget]) {  
              Budget_Line_Item__c newLI = LI.clone(false);
              newLI.Budget__c = budgetId;
             
             items.add(newLI);
         }

       insert items; 
       

    }
    
    public PageReference saveBudget(){   
        
        PageReference pv;
        ID OldBudgetID = ExtCon.getID();
        
        ExtCon.save();
        
        try{
                   
            // Check if it is Save or Clone.
            // If CLone the execute clone line item
           // Then redirect to new budget ID.  
            
            if(OldBudgetID != ExtCon.getID()){
            
                cloneLineItem(ExtCon.getID(), OldBudgetID);     
                
                BudgetRecord = (Budget__c)this.ExtCon.getRecord();
                Budget__c newBudgetRecord = [select id from Budget__c where id=:ExtCon.getID()];
                
                pv = new Pagereference('/'+ExtCon.getID()+'/e');
            }

        }catch(Exception e){
            ApexPages.Message emsg = new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage());    
            ApexPages.addMessage(emsg);
        }        
        
        //pv.getParameters().put('id', ExtCon.getID());
        //return pv.setRedirect(true);
        return pv;
    }
    
   
}