metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Market_Class__c</fullName>
        <label>Market Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment_Sub_Class__c</fullName>
        <label>Market Segment Sub Class</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K-12</fullName>
                </value>
                <value>
                    <fullName>Higher Education</fullName>
                </value>
                <value>
                    <fullName>Border Patrol</fullName>
                </value>
                <value>
                    <fullName>Bureau of Land Management</fullName>
                </value>
                <value>
                    <fullName>Central Intelligence Agency (CIA)</fullName>
                </value>
                <value>
                    <fullName>General Services Admin (GSA)</fullName>
                </value>
                <value>
                    <fullName>Department of Agriculture (USDA)</fullName>
                </value>
                <value>
                    <fullName>Department of Commerce</fullName>
                </value>
                <value>
                    <fullName>Department of Defense (DOD)</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>Navy</fullName>
                </value>
                <value>
                    <fullName>Air Force</fullName>
                </value>
                <value>
                    <fullName>Marine Corps</fullName>
                </value>
                <value>
                    <fullName>Coast Guard</fullName>
                </value>
                <value>
                    <fullName>Department of Education</fullName>
                </value>
                <value>
                    <fullName>Department of Energy</fullName>
                </value>
                <value>
                    <fullName>Department of Health &amp; Human Services</fullName>
                </value>
                <value>
                    <fullName>Department of Homeland Security (DHS)</fullName>
                </value>
                <value>
                    <fullName>Department of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Department of Justice (DOJ)</fullName>
                </value>
                <value>
                    <fullName>Department of Labor (DOL)</fullName>
                </value>
                <value>
                    <fullName>Department of State (DOS)</fullName>
                </value>
                <value>
                    <fullName>Department of the Interior</fullName>
                </value>
                <value>
                    <fullName>Department of the Treasury</fullName>
                </value>
                <value>
                    <fullName>Department of Transportation</fullName>
                </value>
                <value>
                    <fullName>Department of Veterans Affairs (VA)</fullName>
                </value>
                <value>
                    <fullName>Federal Bureau of Investigation (FBI)</fullName>
                </value>
                <value>
                    <fullName>Fish and Wildlife Service</fullName>
                </value>
                <value>
                    <fullName>National Guard</fullName>
                </value>
                <value>
                    <fullName>National Park Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Class__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Program (MRP)</fullName>
                </value>
                <value>
                    <fullName>Non-Program</fullName>
                </value>
                <value>
                    <fullName>High-Net-Worth (HNW)</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Industrial &amp; Commercial</fullName>
                </value>
                <value>
                    <fullName>Multi Family</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>State/Municipal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Site_Address__c</fullName>
        <description>Address of job project site</description>
        <label>Project Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <description>City of job project site</description>
        <label>Project Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <description>Project Site State</description>
        <label>Project Site State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Zipcode__c</fullName>
        <description>Project Site Zipcode</description>
        <label>Project Site Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property ID</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Class__c</fullName>
        <label>Market Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Non-Residential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment_Sub_Class__c</fullName>
        <label>Market Segment Sub Class</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Segment__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K-12</fullName>
                </value>
                <value>
                    <fullName>Higher Education</fullName>
                </value>
                <value>
                    <fullName>Border Patrol</fullName>
                </value>
                <value>
                    <fullName>Bureau of Land Management</fullName>
                </value>
                <value>
                    <fullName>Central Intelligence Agency (CIA)</fullName>
                </value>
                <value>
                    <fullName>General Services Admin (GSA)</fullName>
                </value>
                <value>
                    <fullName>Department of Agriculture (USDA)</fullName>
                </value>
                <value>
                    <fullName>Department of Commerce</fullName>
                </value>
                <value>
                    <fullName>Department of Defense (DOD)</fullName>
                </value>
                <value>
                    <fullName>Army</fullName>
                </value>
                <value>
                    <fullName>Navy</fullName>
                </value>
                <value>
                    <fullName>Air Force</fullName>
                </value>
                <value>
                    <fullName>Marine Corps</fullName>
                </value>
                <value>
                    <fullName>Coast Guard</fullName>
                </value>
                <value>
                    <fullName>Department of Education</fullName>
                </value>
                <value>
                    <fullName>Department of Energy</fullName>
                </value>
                <value>
                    <fullName>Department of Health &amp; Human Services</fullName>
                </value>
                <value>
                    <fullName>Department of Homeland Security (DHS)</fullName>
                </value>
                <value>
                    <fullName>Department of Housing and Urban Development</fullName>
                </value>
                <value>
                    <fullName>Department of Justice (DOJ)</fullName>
                </value>
                <value>
                    <fullName>Department of Labor (DOL)</fullName>
                </value>
                <value>
                    <fullName>Department of State (DOS)</fullName>
                </value>
                <value>
                    <fullName>Department of the Interior</fullName>
                </value>
                <value>
                    <fullName>Department of the Treasury</fullName>
                </value>
                <value>
                    <fullName>Department of Transportation</fullName>
                </value>
                <value>
                    <fullName>Department of Veterans Affairs (VA)</fullName>
                </value>
                <value>
                    <fullName>Federal Bureau of Investigation (FBI)</fullName>
                </value>
                <value>
                    <fullName>Fish and Wildlife Service</fullName>
                </value>
                <value>
                    <fullName>National Guard</fullName>
                </value>
                <value>
                    <fullName>National Park Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market_Class__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Program (MRP)</fullName>
                </value>
                <value>
                    <fullName>Non-Program</fullName>
                </value>
                <value>
                    <fullName>HNW</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Federal Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Industrial &amp; Commercial</fullName>
                </value>
                <value>
                    <fullName>Multi Family</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>State/Municipal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Property_Queueable_Update.cls
public without sharing class Property_Queueable_Update implements Queueable{
        public final List<ATI_Job__c> jobsToUpdate;
        public final Map<Id,Property__c> propMap;
        public final String TypeQueue;

        public Property_Queueable_Update(List<ATI_Job__c> jobsRecieived, Map<Id,Property__c> propMapRecieved, String Type)
        {
            jobsToUpdate = jobsRecieived;
            propMap = propMapRecieved;
            TypeQueue = Type;
        }

        public void execute(QueueableContext context) 
        {
            system.debug('Jobs to update is ' + jobsToUpdate);
            for(ATI_Job__c job : jobsToUpdate)
            {
                Property__c prop = PropMap.get(job.Property_ID__c);
                if(TypeQueue == 'MarketChange')
                {
                    job.Market_Class__c = prop.Market_Class__c;
                    job.Market_Segment__c = prop.Market_Segment__c;
                    job.Market_Segment_Sub_Class__c = prop.Market_Segment_Sub_Class__c; 
                }
                if(TypeQueue == 'AddressChange')
                {
                    job.Project_Site_Address__c = prop.Address_line_1__c;
                    job.Project_Site_City__c = prop.City__c;
                    job.Project_Site_State__c = prop.State__c;
                    job.Project_Site_Zipcode__c = prop.Zip__c;
                }
                
                
            }
            update jobsToUpdate;
        }

}