metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATI_Job__c/fields/Google_Drive_Folder_Ref__c.field-meta.xml
<CustomField>
    <fullName>Google_Drive_Folder_Ref__c</fullName>
    <label>Google Drive Folder Ref</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/SharinPix_Deleted_Images__c.object-meta.xml
<CustomObject>
    <label>SharinPix Deleted Images</label>
    <nameField>
        <displayFormat>SDI-{0000}</displayFormat>
        <label>SharinPix Deleted Images Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SharinPix Deleted Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>ATI_Job__c</referenceTo>
    <relationshipLabel>SharinPix Deleted Images</relationshipLabel>
    <relationshipName>SharinPix_Deleted_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SharinPix_Deleted_Images__c/fields/Old_SharinPix_record_ID__c.field-meta.xml
<CustomField>
    <fullName>Old_SharinPix_record_ID__c</fullName>
    <label>Old SharinPix record ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SharinPixResyncController.cls
public class SharinPixResyncController {

    public class MulesoftAPIException extends Exception {}
    
    @AuraEnabled
    public static String executeJob(String JobId){
    	String message = SharinPix_Constants.STRING_EMPTY;
        String body = SharinPix_Constants.STRING_EMPTY;
        System.debug('JobID-----'+ JobId);
        ATI_Job__c Job = [select Id, Google_Drive_Folder_Ref__c from ATI_Job__c where Id =: JobId];
        List<sharinpix__SharinPixImage__c> allSharinPixImages = new List<sharinpix__SharinPixImage__c>([select id from sharinpix__SharinPixImage__c where Job__c =: JobId]);
        List<SharinPix_Deleted_Images__c> allSharinPixDelImages = new List<SharinPix_Deleted_Images__c>([select Old_SharinPix_record_ID__c from SharinPix_Deleted_Images__c where Job__c =: JobId]);
        
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('Job', Job.id);
        gen.writeStringField('ParentGDID', Job.Google_Drive_Folder_Ref__c);        
        gen.writeFieldName('CurrentImages');
    	gen.writeStartArray();
            for(sharinpix__SharinPixImage__c asi :allSharinPixImages){
                gen.writeStartObject();
                gen.writeStringField('Id', asi.Id);
                gen.writeEndObject();
            }
    	gen.writeEndArray();        
        gen.writeFieldName('DeletedImages');
    	gen.writeStartArray();
            for(SharinPix_Deleted_Images__c asdi :allSharinPixDelImages){
                gen.writeStartObject();
                gen.writeStringField('Id', asdi.Old_SharinPix_record_ID__c);
                gen.writeEndObject();
            }
    	gen.writeEndArray();
        
        gen.writeEndObject();
        body = gen.getAsString(); 
        
        System.debug('body---------->'+body);
        
        
        HttpResponse res1;
        res1 = ResyncAPI(body);
        
        
        String str=res1.getbody();
        Integer Status = res1.getStatusCode();
        System.debug('******* Result ResyncAPI API function - ' + str);
        if(Status == 200 || Status == 201){
        	message = 'Success';
        }
        else{
            message = 'Error';
        }
        
        return message;
        
        
    }

    @TestVisible
    private static HttpResponse ResyncAPI(String Body) {
        if(String.isBlank(Body))
            throw new MulesoftAPIException(SharinPix_Constants.APIERROR_BODYISEMPTY); 
        
        Http http = new Http();
        HttpRequest req1 = new HttpRequest();
        
        req1.setEndpoint(SharinPix_Constants.ENDPOINTURL + SharinPix_Constants.API_RESYNC);
        req1.setmethod(SharinPix_Constants.HTTPREQMETHOD_POST);
        req1.setHeader('Content-Type', SharinPix_Constants.CONTENTTYPE_JSON); 
        req1.setTimeout(20000);
        req1.setbody(body);
        
        HttpResponse res1;
        res1 = http.send(req1);
        
        return res1;
    }
}