metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_of_Loss__c</fullName>
        <description>Field to indicate date of loss</description>
        <label>Date of Loss</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Master_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Job</label>
        <referenceTo>Master_Job__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <description>City of job project site</description>
        <label>Project Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <description>Project Site State</description>
        <label>Project Site State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Master_Job__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_Loss__c</fullName>
        <label>Date of Loss</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Address_Line_1__c</fullName>
        <formula>Property__r.Address_Line_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site Address Line 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <formula>Property__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <formula>Property__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site State</label>
        <type>Text</type>
    </fields>
    <label>Master Job</label>
    <nameField>
        <label>Master Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/classes/BatchForMasterJobs.cls
global class BatchForMasterJobs implements Database.Batchable<sObject> {
    global String Query;
    global final String Entity;
    global final String Field;
    global final String Value;
    Map<Id,Master_Job__c> outscopeToUpdate = new Map<Id, Master_Job__c>();
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator(query);
    }
    
  
    global void execute(Database.BatchableContext BC, List<ATI_Job__c> scope)
    {
        
        Set<Id> masterjobset = new Set<Id>(); 
        Map<Id,Master_Job__c> scopeToUpdate = new Map<Id, Master_Job__c>();
        for(ATI_Job__c s : scope)
        {
            Master_Job__c mj = new Master_Job__c(Id = s.Master_Job__c);
            scopeToUpdate.put(s.Master_Job__c, mj);
        }
        
        for(Id s : scopeToUpdate.keyset())
        {
            if(outscopeToUpdate.containsKey(s))
            {
                scopeToUpdate.get(s).Amount__c = outscopeToUpdate.get(s).Amount__c;
            }
        }
        for(ATI_Job__c s : scope)
        {
            if(s.Amount__c == null)
            {
                s.Amount__c = 0;
            }
            
            if(outscopeToUpdate.containsKey(s.Master_Job__c))
            {
                scopeToUpdate.get(s.Master_Job__c).Amount__c = scopeToUpdate.get(s.Master_Job__c).Amount__c + s.Amount__c;
                outscopeToUpdate.get(s.Master_Job__c).Amount__c = outscopeToUpdate.get(s.Master_Job__c).Amount__c;

            }
            if(scopeToUpdate.get(s.Master_Job__c).Amount__c == null)
            {
                scopeToUpdate.get(s.Master_Job__c).Amount__c = 0;
            }
            if(!outscopeToUpdate.containsKey(s.Master_Job__c))
            {
                
                scopeToUpdate.get(s.Master_Job__c).Amount__c = scopeToUpdate.get(s.Master_Job__c).Amount__c + s.Amount__c;
                outscopeToUpdate.put(s.Master_Job__c, scopeToUpdate.get(s.Master_Job__c));
            }
            
        }
        update scopeToUpdate.values();
         
    }     
         
        global void finish(Database.BatchableContext BC){
        }
     }

    //  if(s.Date_Of_Loss__c != null)
    //         {
    //         s.Name = s.Job_Address_Line_1__c + ' ' + s.Project_Site_City__c + ' ' + s.Project_Site_State__c + ' | ' + s.Date_Of_Loss__c;
    //         s.Name = s.Name.replace('00:00:00', '');
    //         if(s.name.length() > 79){
    //              s.name = s.name.substring(0, 79);
    //         }
    //           }else{
    //              s.Name = s.Job_Address_Line_1__c + ' ' + s.Project_Site_City__c + ' ' + s.Project_Site_State__c;
    //              s.Name = s.Name.replace('00:00:00', '');
    //              if(s.name.length() > 79){
    //                  s.name = s.name.substring(0, 79);
    //              }
    //           }
    //          props.add(s);
    //         }
    //       if(!props.isEmpty()){
    //          update props; 
    //         }