metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Insurance_Adjuster_Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Insurance Adjuster/Broker for this Job-- referenced in New Job VF page</description>
        <label>Insurance Adjuster/Broker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Insurance Adjuster/Broker)</relationshipLabel>
        <relationshipName>ATIJobIAB1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Insurance Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Jobs (Insurance Company)</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchForJobs_Test.cls
@isTest
private with sharing class BatchForJobs_Test {
    static testMethod void BatchForJobs_Test() {
        Id u2 = UserInfo.getUserId();
        
        system.runAs(new User(Id=Userinfo.getUserId())){
            ObjectInserts objectinfo = TestDataUtil.createObjects(5, true);
            objectinfo.accountroleList[0].Multiple_Roles__c = 'Insurance Adjuster/Company';
            update objectinfo.accountroleList;
            BatchForJobs b = new BatchForJobs();
            b.query = 'Select Id, Insurance_Company__c, Insurance_Adjuster_Broker__c FROM ATI_Job__c';
            Id ba = Database.executeBatch(b);
        }
    }
}