metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>AE_1_Bonus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE 1 Bonus</label>
        <referenceTo>AE_Bonus__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>ATIAEBonus1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AE_2_Bonus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE 2 Bonus</label>
        <referenceTo>AE_Bonus__c</referenceTo>
        <relationshipLabel>Jobs (AE 2 Bonus)</relationshipLabel>
        <relationshipName>ATIAEBonus2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Account does not exist or has been rejected.</errorMessage>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Rejected</value>
            </filterItems>
            <filterItems>
                <field>Account.Status__c</field>
                <operation>notEqual</operation>
                <value>Rejected</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ATI Jobs</relationshipLabel>
        <relationshipName>ATI_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ATI_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ATI Job</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>AE_1_Bonus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE 1 Bonus</label>
        <referenceTo>AE_Bonus__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AE_2_Bonus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE 2 Bonus</label>
        <referenceTo>AE_Bonus__c</referenceTo>
        <relationshipLabel>Invoices (AE 2 Bonus)</relationshipLabel>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ATI_Job__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ATI Job</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Due__c</fullName>
        <formula>((Total_Costs_Per_Contract__c  +  Total_Tax__c) - retainage_amount__c)- Total_Credits__c -  Payment_Adjustment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Costs on Contract + Tax less Retainage - Amounts Received - Payments/ Adjustments</inlineHelpText>
        <label>Net Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceTriggerUtility.cls
// trigger utility class for invoice
public without sharing class InvoiceTriggerUtility {
    public static void beforeInvoiceInsert( List<Invoice__c> newInvoices ){
        populateAEsOnInvoices( newInvoices );
    }
        
    public static void populateAEsOnInvoices( List<Invoice__c> newInvoices ){
        Set<Id> JobIds = new Set<Id>();
        Map<Id, ATI_Job__c> JobsMap = new Map<Id, ATI_Job__c>();
        for( Invoice__c inv : newInvoices ){
            if( inv.ATI_Job__c != null ){
                JobIds.add( inv.ATI_Job__c );
            }
        }
        if( !JobIds.isEmpty() ){
            JobsMap = new Map<id, ATI_Job__c>( [ SELECT Id, AE_1_Bonus__c, AE_2_Bonus__c, Account__r.Type 
                                                  FROM ATI_Job__c 
                                                  WHERE Id IN: JobIds ] );
            for( Invoice__c inv : newInvoices ){
                if( inv.ATI_Job__c != null ){
                    inv.AE_1_Bonus__c = JobsMap.get( inv.ATI_Job__c ).AE_1_Bonus__c;
                    inv.AE_2_Bonus__c = JobsMap.get( inv.ATI_Job__c ).AE_2_Bonus__c;
                }
            }
        }
    }
    public static void CloseRelatedCases(list<Invoice__c> invoices, Map<Id, Invoice__c> oldInvoice)
    {
        Map<Id, Invoice__c> invoicesPassed = new Map<Id, Invoice__c>();
        for(invoice__c inv : invoices)
        {
            if(inv.Net_Due__c == 0 && oldInvoice.get(inv.Id).Net_Due__c > 0)
            {
                invoicesPassed.put(inv.Id, inv);
            }
        }
        if(!invoicesPassed.isEmpty())
        {
            List<Case> invCases = [Select Id, status, Related_Invoice__c FROM 
                                Case Where Related_Invoice__c =: oldInvoice.keyset()];
            for(Case cse : invCases)
            {
                cse.Status = 'Closed';
                
            }
            if(invCases.isEmpty())
            {
                update invCases;
            }
        }
    }
}