metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Created</fullName>
                    <default>true</default>
                    <label>Not Created</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Job Name field is used on New Job VF page, used to pass along to Timberline, and used to update Opportunity Name field via &apos;Opportunity Naming Convention&apos; workflow.</description>
        <label>Job Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Number__c</fullName>
        <description>Job unique identifier/external ID populated via code.  Numbers are representative of Office, Division, PM ID, and Year.</description>
        <externalId>true</externalId>
        <label>Job Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Manager assigned to this job</description>
        <label>Project Director</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Executive Management, Project Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobpm1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Estimating/Review</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                </value>
                <value>
                    <fullName>Billing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trade__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Trade</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XACT_File_Reopened__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>XACT File Reopened</label>
        <type>Checkbox</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>ATI_Job__c</fullName>
        <label>Job</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets_PM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Costs_BL__c</fullName>
        <description>For XactAnalysis estimate import to budget</description>
        <label>Actual Costs BL</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Budget Line Items</relationshipLabel>
        <relationshipName>Budget_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bypass_Calculation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Calculation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <label>Equipment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>From_Xact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>From Xact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GP__c</fullName>
        <description>For XactAnalysis estimate import to budget</description>
        <label>GP %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_House_Hours__c</fullName>
        <label>In-House Hours</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>In_House_Rate__c</fullName>
        <label>In-House Rate</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_sub_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is sub Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Item Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Materials__c</fullName>
        <label>Materials</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Costs__c</fullName>
        <label>Other Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Selector__c</fullName>
        <label>Selector</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcontractor_bid__c</fullName>
        <label>Subcontractor bid</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trade_Option__c</fullName>
        <label>Trade Option</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACT Acoustical Treatments</fullName>
                </value>
                <value>
                    <fullName>APP Appliances</fullName>
                </value>
                <value>
                    <fullName>AWN Awnings &amp; Patio Covers</fullName>
                </value>
                <value>
                    <fullName>CAB Cabinetry</fullName>
                </value>
                <value>
                    <fullName>CLN Cleaning</fullName>
                </value>
                <value>
                    <fullName>CNC/MAS Concrete/Masonary</fullName>
                </value>
                <value>
                    <fullName>CON Contents</fullName>
                </value>
                <value>
                    <fullName>CPS Contents: Packaging, Handling, and Storage</fullName>
                </value>
                <value>
                    <fullName>CRD Credit</fullName>
                </value>
                <value>
                    <fullName>DMO General Demolition</fullName>
                </value>
                <value>
                    <fullName>DOR Doors</fullName>
                </value>
                <value>
                    <fullName>DRY Drywall</fullName>
                </value>
                <value>
                    <fullName>ELE Electrical</fullName>
                </value>
                <value>
                    <fullName>ELS Electrical Special Systems</fullName>
                </value>
                <value>
                    <fullName>EQU Heavy Equipment</fullName>
                </value>
                <value>
                    <fullName>EXC Excavation</fullName>
                </value>
                <value>
                    <fullName>FCC Floor Covering Carpet</fullName>
                </value>
                <value>
                    <fullName>FCR Floor Covering Resilient</fullName>
                </value>
                <value>
                    <fullName>FCS Floor Covering Stone</fullName>
                </value>
                <value>
                    <fullName>FCT Floor Covering Ceramic Tile</fullName>
                </value>
                <value>
                    <fullName>FCV Floor Covering Vinyl</fullName>
                </value>
                <value>
                    <fullName>FCW Floor Covering Wood</fullName>
                </value>
                <value>
                    <fullName>FEE Permits and Fees</fullName>
                </value>
                <value>
                    <fullName>FEN Fencing</fullName>
                </value>
                <value>
                    <fullName>FNC Finish Carpentry</fullName>
                </value>
                <value>
                    <fullName>FNH Finish Hardware</fullName>
                </value>
                <value>
                    <fullName>FPL Fireplaces</fullName>
                </value>
                <value>
                    <fullName>FPS Fire Protection Systems</fullName>
                </value>
                <value>
                    <fullName>FRM Framing &amp; Rough Carpentry</fullName>
                </value>
                <value>
                    <fullName>GLS Glass, Glazing, &amp; Storefronts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trade__c</fullName>
        <label>Trade</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X10_10_Allocation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>10% overhead and 10% profit.</description>
        <label>10/10 Allocation</label>
        <type>Checkbox</type>
    </fields>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{YYYY}{MM}{DD}-{00}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BudgetLineItemFieldUpdateTest.cls
@isTest
public class BudgetLineItemFieldUpdateTest {

/*    public static TestMethod void runTestOnOffice()
    {
        TestDataUtil.createCustomSettings_TriggerStatus();
        
        List<user> users = TestDataUtil.createUsersNew(2, true);
         Account acc = new account(Name = 'Test Account');
        insert acc;
        
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Number__c = '1111-00',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id );
        insert job;
        ATI_Job__c job2 = new ATI_Job__c(Name = 'Test Job',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = FALSE,Project_Manager__c =users[0].id );
        insert job2;
        job2.XACT_File_Reopened__c = TRUE;
        update job2;
        
        Budget__c bud = new Budget__c(Name = 'Test Budget',ATI_Job__c = job.id);
        insert bud;
        
        Budget_Line_Item__c bli = new Budget_Line_Item__c(Budget__c = bud.id,Trade__c = 'FRM',Item_Description__c = '#2 &amp; better');
        insert bli;
        
        Budget_Line_Item__c bli1 = [Select id, Item_Description__c from Budget_Line_Item__c where id =: bli.id];
         System.assertEquals('#2 & better', bli1.Item_Description__c);
        
        Budget_Line_Item__c bli2 = new Budget_Line_Item__c(Budget__c = bud.id,Trade__c = 'FRM',Trade_Option__c = 'Others', Item_Description__c = '#2 &amp; better');
        insert bli2;
        
        BudgetLineItemFieldUpdate.InsertErrortLogForTrade(new List<Budget_Line_Item__c>{bli2});
        BudgetLineItemFieldUpdate.RecalconDelete(new List<Budget_Line_Item__c>{bli2});
        delete bli2;
    }
*/    
     public static TestMethod void UpdateOverheadProfitTest()
    {
         TestDataUtil.createCustomSettings_TriggerStatus();
        Map<id,Budget_Line_Item__c> budLineMap = new Map<Id,Budget_Line_Item__c>();
        
        List<user> users = TestDataUtil.createUsersNew(2, true);
         Account acc = new account(Name = 'Test Account');
        insert acc;
        
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Number__c = '1111-00',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id );
        insert job;
        
        Budget__c bud = new Budget__c(Name = 'Test Budget',ATI_Job__c = job.id);
        insert bud;
        
        Budget_Line_Item__c bli = new Budget_Line_Item__c(Budget__c = bud.id,Trade__c = 'FRM',Item_Description__c = '#2 &amp; better');
        bli.X10_10_Allocation__c = true;
        bli.Revenue__c = 30.0;
        bli.Selector__c = null;
        insert bli;
        
        CheckRecursiveOnBLIUpdate.run = true;
        update bli; 
        budLineMap.put(bli.id,bli);
        BudgetLineItemFieldUpdate.UncheckBypass(new List<Budget_Line_Item__c>{bli},budLineMap);
        CheckRecursiveOnBLIUpdate.run = true;
        delete bli;
        
        
    }
    
    @isTest
    Public static void CreateParentforEstimateItemTest(){
        
        TestDataUtil.createCustomSettings_TriggerStatus();
        Map<id,Budget_Line_Item__c> budLineMap = new Map<Id,Budget_Line_Item__c>();
        
        List<user> users = TestDataUtil.createUsersNew(2, true);
         Account acc = new account(Name = 'Test Account');
        insert acc;
        
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Number__c = '1111-00',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id );
        insert job;
        
        Budget__c bud = new Budget__c(Name = 'Test Budget',ATI_Job__c = job.id);
        insert bud;
        
        Budget_Line_Item__c bli = new Budget_Line_Item__c(Budget__c = bud.id,Trade__c = 'FRM FRAMING & ROUGH CARPENTRY',Item_Description__c = '#2 &amp; better');
        bli.X10_10_Allocation__c = true;
        bli.Revenue__c = 30.0;
        bli.Selector__c = null;
        bli.Subcontractor_bid__c = 76;
        bli.In_House_Hours__c = 98;
        bli.Equipment__c = 53.0;
        bli.Materials__c = 80.0;
        bli.In_House_Rate__c = 98;
        bli.GP__c = 58;
        bli.Other_Costs__c = 70.0;
        
        insert bli;
        
        Map<Id,Budget_Line_Item__c> budLineItemMap = new Map<id,Budget_Line_Item__c>();
        budLineItemMap.put(bli.id,bli);
        
        Budget_Line_Item__c bli1 = new Budget_Line_Item__c();
        bli1 = bli;
        
        bli1.Is_sub_Parent__c = True;
        bli1.Bypass_Calculation__c = false;
        bli1.Equipment__c  = 35.0;
        bli1.In_House_Hours__c = 89;
        bli1.Subcontractor_bid__c = 67;
        bli1.Materials__c = 90.0;
        bli1.Actual_Costs_BL__c = 78;
        bli1.GP__c = 85;
        bli1.Other_Costs__c = 90.0;
        bli1.Trade__c = 'FRM FRAMING & ROUGH CARPENTRY';
        update bli1;
        
        BudgetLineItemFieldUpdate.CreateParentforEstimateItem(new List<Budget_Line_Item__c>{bli1},budLineItemMap);
        BudgetLineItemFieldUpdate.CreateParentforEstimateItem(new List<Budget_Line_Item__c>{bli1},null);
       

        
    }
    
    @isTest
    Public static void CreateSubParentforEstimateItemTest(){
        
        TestDataUtil.createCustomSettings_TriggerStatus();
        Map<id,Budget_Line_Item__c> budLineMap = new Map<Id,Budget_Line_Item__c>();
        
        List<user> users = TestDataUtil.createUsersNew(2, true);
         Account acc = new account(Name = 'Test Account');
        insert acc;
        
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Number__c = '1111-00',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id );
        insert job;
        
        Budget__c bud = new Budget__c(Name = 'Test Budget',ATI_Job__c = job.id);
        insert bud;
        
        Budget_Line_Item__c bli = new Budget_Line_Item__c(Budget__c = bud.id,Trade__c = 'FRM FRAMING & ROUGH CARPENTRY',Item_Description__c = '#2 &amp; better');
        bli.X10_10_Allocation__c = true;
        bli.Revenue__c = 30.0;
        bli.Selector__c = null;
        bli.Subcontractor_bid__c = 76;
        bli.In_House_Hours__c = 98;
        bli.Equipment__c = 53.0;
        bli.Materials__c = 80.0;
        bli.In_House_Rate__c = 98;
        bli.GP__c = 58;
        bli.Other_Costs__c = 70.0;
        
        insert bli;
        
        Map<Id,Budget_Line_Item__c> budLineItemMap = new Map<id,Budget_Line_Item__c>();
        budLineItemMap.put(bli.id,bli);
        
        Budget_Line_Item__c bli1 = new Budget_Line_Item__c();
        bli1 = bli;
        
        bli1.Is_sub_Parent__c = True;
        bli1.Bypass_Calculation__c = false;
        bli1.Equipment__c  = 35.0;
        bli1.In_House_Hours__c = 89;
        bli1.Subcontractor_bid__c = 67;
        bli1.Materials__c = 90.0;
        bli1.Actual_Costs_BL__c = 78;
        bli1.GP__c = 85;
        bli1.Other_Costs__c = 90.0;
        bli1.Trade__c = 'FRM FRAMING & ROUGH CARPENTRY';
        bli1.From_Xact__c = True;
        bli1.Selector__c = 'Test';
        update bli1;
        
        BudgetLineItemFieldUpdate.CreateSubParentforEstimateItem(new List<Budget_Line_Item__c>{bli1});

        
    }
    
     @isTest
    Public static void RollDownCalcforEstimateItemTest(){
        
        TestDataUtil.createCustomSettings_TriggerStatus();
        Map<id,Budget_Line_Item__c> budLineMap = new Map<Id,Budget_Line_Item__c>();
        
        List<user> users = TestDataUtil.createUsersNew(2, true);
         Account acc = new account(Name = 'Test Account');
        insert acc;
        
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Number__c = '1111-00',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id );
        insert job;
        
        Budget__c bud = new Budget__c(Name = 'Test Budget',ATI_Job__c = job.id);
        insert bud;
        
        List<Budget_Line_Item__c> blis = new List<Budget_Line_Item__c>();
        List<Budget_Line_Item__c> updblis = new List<Budget_Line_Item__c>();

        
        Budget_Line_Item__c bl = new Budget_Line_Item__c(Budget__c = bud.id,Trade__c = 'FRM FRAMING & ROUGH CARPENTRY',Item_Description__c = '#2 &amp; better');
        blis.add(bl);
        
        Budget_Line_Item__c bli = new Budget_Line_Item__c(Budget__c = bud.id,Trade__c = 'FRM FRAMING & ROUGH CARPENTRY',Item_Description__c = '#2 &amp; better');
        bli.X10_10_Allocation__c = true;
        bli.Revenue__c = 30.0;
        bli.Selector__c = null;
        bli.Subcontractor_bid__c = 76;
        bli.In_House_Hours__c = 98;
        bli.Equipment__c = 53.0;
        bli.Materials__c = 80.0;
        bli.In_House_Rate__c = 98;
        bli.GP__c = 58;
        bli.Other_Costs__c = 70.0;
        
        blis.add(bli);
        
        insert blis;
        
        Map<Id,Budget_Line_Item__c> budLineItemMap = new Map<id,Budget_Line_Item__c>();
        budLineItemMap.put(blis[0].id,blis[0]);
        budLineItemMap.put(blis[1].id,blis[1]);
        
        Budget_Line_Item__c bli1 = new Budget_Line_Item__c();
        bli1 = blis[0];
        
        Budget_Line_Item__c bli2 = new Budget_Line_Item__c();
        bli2 = blis[1];
        
        bli1.Is_Parent__c = True;
        bli1.Is_sub_Parent__c = True;
        bli1.Bypass_Calculation__c = false;
        bli1.Equipment__c  = 35.0;
        bli1.In_House_Hours__c = 89;
        bli1.Subcontractor_bid__c = 67;
        bli1.Materials__c = 90.0;
        bli1.Actual_Costs_BL__c = 78;
        bli1.GP__c = 85;
        bli1.Other_Costs__c = 90.0;
        bli1.Trade__c = 'FRM FRAMING & ROUGH CARPENTRY';
        updblis.add(bli1);
        
        bli2.Is_Parent__c = True;
        bli2.Is_sub_Parent__c = True;
        bli2.Bypass_Calculation__c = false;
        bli2.Equipment__c  = 38.0;
        bli2.In_House_Hours__c = 109;
        bli2.Subcontractor_bid__c = 47;
        bli2.Materials__c = 20.0;
        bli2.Actual_Costs_BL__c = 38;
        bli2.GP__c = 55;
        bli2.Other_Costs__c = 10.0;
        bli2.Trade__c = 'FRM FRAMING & ROUGH CARPENTRY';
        
        updblis.add(bli2);

        update updblis;
        
        BudgetLineItemFieldUpdate.RollDownCalcforEstimateItem(updblis,budLineItemMap);       

        
    }
    
}