metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Project_Site_Address__c</fullName>
        <description>Address of job project site</description>
        <label>Project Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <description>City of job project site</description>
        <label>Project Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <description>Project Site State</description>
        <label>Project Site State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Zipcode__c</fullName>
        <description>Project Site Zipcode</description>
        <label>Project Site Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property ID</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternate_Name__c</fullName>
        <label>Alternate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PropertyTriggerHandler.cls
public with sharing class PropertyTriggerHandler {
    public static void PropertyNameFormat(List<Property__c> props) {
        
        for(property__c prop : props){
            if(prop.Address_Line_1__c != null && prop.City__c != null && prop.State__c != null){
                prop.Name = prop.Address_Line_1__c + ' ' + prop.City__c + ' ' + prop.State__c; 
            
            if(prop.Alternate_Name__c != null){
                prop.Name = prop.Name + ' | ' + prop.Alternate_Name__c;
            }
            if(prop.name.length() > 79){
                prop.name = prop.name.substring(0, 79);
        }
    }
        }

    }
    public static void PropertyNameUpdate(List<Property__c> newProps, map<Id,Property__c> oldProps, Map<Id,Property__c> newPropMap){
        Set<Id> propset = new Set<Id>();
        List<ATI_Job__c> jobs = new List<ATI_Job__c>();
        for(Property__c prop : newProps){
            Property__c oldProp = oldProps.get(prop.id);
            if(prop.Address_line_1__c != oldProp.Address_line_1__c || prop.City__c != oldProp.City__c || prop.State__c != oldProp.State__c || 
            prop.Zip__c != oldProp.Zip__c || prop.Alternate_Name__c != oldProp.Alternate_Name__c){
                propSet.add(prop.id);
                if(prop.Alternate_Name__c == null){
                    prop.Name = prop.Address_Line_1__c + ' ' + prop.City__c + ' ' + prop.State__c;
                }else{
                    prop.Name = prop.Address_Line_1__c + ' ' + prop.City__c + ' ' + prop.State__c + ' | ' + prop.Alternate_Name__c;  
                }
                if(prop.name.length() > 79){
                    prop.name = prop.name.substring(0, 79);
            }
            
        }
    }
//     if(!propset.isEmpty()){
//         jobs = [Select Id, Project_Site_Address__c, Project_Site_City__c, Project_Site_State__c, Project_Site_Zipcode__c, Property_ID__c FROM 
//         ATI_Job__c WHere Property_Id__c =: propset];
//     }
//     if(!jobs.isEmpty()){
//     for(ATI_Job__c job: jobs){
//         Property__c prop = newPropMap.get(job.Property_ID__c);
//         job.Project_Site_Address__c = prop.Address_line_1__c;
//         job.Project_Site_City__c = prop.City__c;
//         job.Project_Site_State__c = prop.State__c;
//         job.Project_Site_Zipcode__c = prop.Zip__c;
//     }
//     update jobs;
// }
    
    }
}