metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <description>Field to indicate claim number for jobs that will be covered by insurance.</description>
        <label>Claim #</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Loss__c</fullName>
        <description>Field to indicate date of loss</description>
        <label>Date of Loss</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address__c</fullName>
        <description>Address of job project site</description>
        <label>Project Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <description>City of job project site</description>
        <label>Project Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <description>Project Site State</description>
        <label>Project Site State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Zipcode__c</fullName>
        <description>Project Site Zipcode</description>
        <label>Project Site Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XASP_Transaction_ID__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <externalId>true</externalId>
        <label>XASP Transaction ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MergeJobs.cls
public with sharing class MergeJobs {
    public MergeJobs() {

    }
    @AuraEnabled
    public static List<ATI_Job__c> searchJobs(String searchKey){
        try {
            String searchLikeKey1 =  '%' + searchKey + '%';
            String searchLikeKey = searchLikeKey1.normalizeSpace();
            List<ATI_Job__c> jobs = 
            [SELECT Id, Name, Date_of_Loss__c, Claim__c, Project_Site_Address__c, Project_Site_City__c, 
            Project_Site_State__c, Project_Site_Zipcode__c, XASP_Transaction_ID__c
            FROM ATI_Job__c
            WHERE Name Like : searchLikeKey 
            ORDER BY CreatedDate DESC LIMIT 5];
            
            return jobs;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}