metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Office__c</fullName>
        <description>Field to indicate the ATI office associated with the job.
(Hidden Field) Only for Apex Triggers Code and other reports not for UI.</description>
        <formula>Office2__r.Name</formula>
        <label>Office Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Zipcode__c</fullName>
        <description>Project Site Zipcode</description>
        <label>Project Site Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATI_Job__c/fields/Office_By_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Office_By_Zip_Code__c</fullName>
    <label>Office By Zip Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

metadatafullcopy/unpackaged/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Office__c.object
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Zip_Code__c/Office_Zip_Code__c.object-meta.xml
<CustomObject>
    <label>Office Zip Code</label>
    <nameField>
        <label>Office Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Zip_Code__c/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Office</label>
    <referenceTo>Office__c</referenceTo>
    <relationshipLabel>Office Zip Codes</relationshipLabel>
    <relationshipName>Office_Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateJobZipCodes.cls
global class BatchToUpdateJobZipCodes implements Database.Batchable<sObject> {
  
    global String Query;
    global final String Entity;
    global final String Field;
    global final String Value;
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        return Database.getQueryLocator(Query);
    }
    global void execute(Database.BatchableContext BC, List<ATI_Job__c> scope)
    {
        try{
            List<ATI_Job__c> jobsToUpdate = new List<ATI_Job__c>();
            Set<String> ZipSet = new Set<String>();
            Map<String,Office_Zip_Code__c> offMap = new Map<String,Office_Zip_Code__c>();
            for(ATI_Job__c j : scope)
            {
                if(j.Project_Site_Zipcode__c != null && j.Project_Site_Zipcode__c.length() > 4)
                {
                    string zip = j.Project_Site_Zipcode__c.substring(0, 5);
                    ZipSet.add(zip);
                }
            }
            List<Office_Zip_Code__c> zips = [SELECT Id, Office__c, Office__r.Name, Name
                                            FROM Office_Zip_Code__c 
                                            WHERE NAME =:ZipSet];
            for(Office_Zip_Code__c oz : zips)
            {
                offMap.put(oz.Name, oz);
            }
            for(ATI_Job__c j : scope)
            {
                if(j.Project_Site_Zipcode__c != null && j.Project_Site_Zipcode__c.length() > 4)
                {
                    string zip = j.Project_Site_Zipcode__c.substring(0, 5);
                    if(offMap.containsKey(zip))
                    {
                        Office_Zip_Code__c ozc = offMap.get(zip);
                        j.Office_By_Zip_Code__c = ozc.Office__r.Name;
                        jobsToUpdate.add(j);
                        
                    }
                }
            }
            update jobsToUpdate;
    }catch(Exception e){
        Log__c batcherror = new Log__c( Message__c = e.getMessage());
        insert batcherror;
    }
        
    }
            
        global void finish(Database.BatchableContext BC){
        }
        }