metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Office2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Office object to indicate what office the Job is taking place out of.</description>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>ATIOffice2</relationshipLabel>
        <relationshipName>ATIOffice2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Manager assigned to this job</description>
        <label>Project Director</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Executive Management, Project Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobpm1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>XACT_File_Reopened__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>XACT File Reopened</label>
        <type>Checkbox</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Office__c.object
<CustomObject>
    <fields>
        <fullName>Project_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Admin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Offices80Iv</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/XactFileReOpenedClass.cls
/**
 * @Author: DemandBlue
 * @Description: Class Trigger Email to Project Manager in Job object and Program Admin in Office When a Job is re-opened from XactWare
 * @Ver: 1.0 
**/
public class XactFileReOpenedClass {
    
    public static void TriggerMail(List<ATI_Job__c> Jobs, Map<id, ATI_Job__c> oldMaps){
    
    system.debug('!!!!!!!'+Jobs);
        Set<Id> ATIId = new Set<Id>();
        List<ATI_Job__c> JobRecord = new List<ATI_Job__c>([Select Id,Name,XACT_File_Reopened__c, Project_Manager__r.email, Office2__r.Project_Coordinator__r.email from ATI_Job__c where ID IN: Jobs]);
        system.debug('@@'+JobRecord);
        for(ATI_Job__c job: JobRecord){
            ATI_Job__c oldMap = oldMaps.get(job.Id);
            system.debug('OldMap'+oldMap);
            //if(oldMap.XACT_File_Reopened__c!=job.XACT_File_Reopened__c && job.XACT_File_Reopened__c==true){
            if(oldMap.XACT_File_Reopened__c!=job.XACT_File_Reopened__c && job.XACT_File_Reopened__c==true && (!String.isBlank(job.Project_Manager__r.email) || !String.isBlank(job.Office2__r.Project_Coordinator__r.email))){
                system.debug('Inside If mail'+job.Project_Manager__r.email);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                String[] toAddresses = new String[] {};
                if(!String.isBlank(job.Project_Manager__r.email)){toAddresses.add(job.Project_Manager__r.email);}
                if(!String.isBlank(job.Office2__r.Project_Coordinator__r.email)){toAddresses.add(job.Office2__r.Project_Coordinator__r.email);}
                String RecordURL = URL.getSalesforceBaseUrl().toExternalForm()+'/'+job.Id;
                //Send Email
                system.debug('Send Emails:'+toAddresses);
                mail.setToAddresses(toAddresses);
                mail.setSubject('Job Re-opened in XactAnalysis');
                mail.setHtmlBody('Hi,<br/><br/> This is to inform you that the Job <a href='+RecordURL+'>'+job.Name+'</a> has been re-opened in Xact Analysis. Please review this job in Salesforce and make any necessary changes.');
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                
            }//EOF IF
        }
    }
    public static void TriggerMail(List<ATI_Job__c> Jobs){
        system.debug('!!!!!!!'+Jobs);
        Set<Id> ATIId = new Set<Id>();
        List<ATI_Job__c> JobRecord = new List<ATI_Job__c>([Select Id,Name,XACT_File_Reopened__c, Project_Manager__r.email, Office2__r.Project_Coordinator__r.email from ATI_Job__c where ID IN: Jobs]);
        system.debug('@@'+JobRecord);
        for(ATI_Job__c job: JobRecord){
            
            if(job.XACT_File_Reopened__c==true && (!String.isBlank(job.Project_Manager__r.email) || String.isBlank(job.Office2__r.Project_Coordinator__r.email))){
                system.debug('Inside If mail'+job.Project_Manager__r.email);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                String[] toAddresses = new String[] {};
                if(!String.isBlank(job.Project_Manager__r.email)){toAddresses.add(job.Project_Manager__r.email);}
                if(!String.isBlank(job.Office2__r.Project_Coordinator__r.email)){toAddresses.add(job.Office2__r.Project_Coordinator__r.email);}
                String RecordURL = URL.getSalesforceBaseUrl().toExternalForm()+'/'+job.Id;
                //Send Email
                system.debug('Send Emails:'+toAddresses);
                mail.setToAddresses(toAddresses);
                mail.setSubject('Job Re-opened in XactAnalysis');
                mail.setHtmlBody('Hi,<br/><br/> This is to inform you that the Job <a href='+RecordURL+'>'+job.Name+'</a> has been re-opened in Xact Analysis. Please review this job in Salesforce and make any necessary changes.');
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                
            }//EOF IF
        }//EOF For Loop
    }
    
}