metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <description>Date that the Job&apos;s Stage is set to Complete</description>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Time_Approved__c</fullName>
        <description>Field to indicate the date and time that a job was approved by an admin manager-- populated via &apos;Job Approval Process&apos; Final Approval Action Field Update.</description>
        <label>Date/Time Approved</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>Field to note what major division/service type the job is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asbestos</fullName>
                </value>
                <value>
                    <fullName>Biohazard</fullName>
                </value>
                <value>
                    <fullName>Catastrophes</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contents</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Emergency Svces</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Microbial</fullName>
                </value>
                <value>
                    <fullName>Technical Svces</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ECONZ_Error_Message__c</fullName>
        <label>ECONZ Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ECONZ_Integration_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ECONZ Integration Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ECONZ_Last_Callout_Time__c</fullName>
        <label>ECONZ Last Succcessful Callout Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ECONZ_Task_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ECONZ Task Created?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Job Name field is used on New Job VF page, used to pass along to Timberline, and used to update Opportunity Name field via &apos;Opportunity Naming Convention&apos; workflow.</description>
        <label>Job Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Number__c</fullName>
        <description>Job unique identifier/external ID populated via code.  Numbers are representative of Office, Division, PM ID, and Year.</description>
        <externalId>true</externalId>
        <label>Job Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Prev_Name__c</fullName>
        <label>Job Prev Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Start_Date__c</fullName>
        <description>Field to indicate projected start date of a job</description>
        <inlineHelpText>Auto time stamped when the job is marked won.</inlineHelpText>
        <label>Job Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_FotoIn_Update__c</fullName>
        <label>Last FotoIn Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Successful_FotoIn_Update__c</fullName>
        <label>Last Successful FotoIn Update</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <description>Field to indicate the ATI office associated with the job.
(Hidden Field) Only for Apex Triggers Code and other reports not for UI.</description>
        <formula>Office2__r.Name</formula>
        <label>Office Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Manager assigned to this job</description>
        <label>Project Director</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Executive Management, Project Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobpm1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager_new__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will up updated via process builder depending on the Ops manager and/or Superintendent.</description>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIProjectManagerNew</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address_2__c</fullName>
        <label>Project Site Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Address__c</fullName>
        <description>Address of job project site</description>
        <label>Project Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Call_Result_Message__c</fullName>
        <label>Project Site Call Result Message</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <description>City of job project site</description>
        <label>Project Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Name_Fotoin__c</fullName>
        <description>two spaces between number and name</description>
        <formula>Job_Number__c + &quot;  &quot; +  Job_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site Name Fotoin</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Name__c</fullName>
        <description>Project site name</description>
        <label>Project Site Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Record_Id__c</fullName>
        <externalId>true</externalId>
        <label>Project Site Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <description>Project Site State</description>
        <label>Project Site State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_Zipcode__c</fullName>
        <description>Project Site Zipcode</description>
        <label>Project Site Zipcode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Estimating/Review</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                </value>
                <value>
                    <fullName>Billing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>year__c</fullName>
        <formula>TEXT(YEAR(DATEVALUE( Date_Time_Taken__c )))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>year</label>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Office__c.object
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ECONZ_Integration_RetryBatch.cls
//ECONZ_Integration_RetryBatch

global class ECONZ_Integration_RetryBatch implements Database.Batchable<SObject>,Database.AllowsCallouts{
    global string strQuery;
    
    global ECONZ_Integration_RetryBatch(string condition){
        strQuery = 'SELECT Id, Name, Stage__c, Recordtype.id, Job_Name__c, Project_Manager_New__r.Email, Project_Manager_New__r.Name, Project_Manager__r.Name, Division__c, Office__c, Job_Start_Date__c, Date_Time_Approved__c, Job_Prev_Name__c,Project_Site_Address_2__c, Project_Site_Address__c, Project_Site_City__c, Project_Site_State__c, Completion_Date__c, Project_Manager_New__r.EConz_Primary_Key__c,Project_Site_Zipcode__c, ECONZ_Error_Message__c, ECONZ_Integration_Error__c, ECONZ_Last_Callout_Time__c, ECONZ_Task_Created__c, Project_Site_Name_Fotoin__c,Project_Site_Record_Id__c, Project_Site_Call_Result_Message__c, Last_Successful_FotoIn_Update__c, Last_FotoIn_Update__c, Project_Site_Name__c, year__c, job_number__c FROM ATI_Job__c WHERE (ECONZ_Integration_Error__c = true AND Job_Start_Date__c != NULL) OR (Job_Start_Date__c != NULL AND ECONZ_Task_Created__c = false AND Stage__c = \'Won\')';
                        system.debug('----Query---'+strQuery);

        if(!string.isEmpty(condition))
            strQuery = strQuery +  ' AND ' + condition;
    }
    
    global database.Querylocator start(Database.batchableContext bc){   
                system.debug('----Query---'+strQuery);

        return Database.getQueryLocator(strQuery);
    }
            
    global void execute(Database.BatchableContext BC, list<ATI_JOb__c> sobjlist){ 
        for(ATI_Job__c obj : sobjlist){
            //ATI_Job__c Job = (ATI_Job__c) obj;
            if(!Test.isRunningTest())
                Econz_Integration_Callouts.invokeIntegration(obj.Id);
        }
    }
                
    global void finish(Database.BatchableContext BC){ 
                        
    }

}