metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Created</fullName>
                    <default>true</default>
                    <label>Not Created</label>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Job Name field is used on New Job VF page, used to pass along to Timberline, and used to update Opportunity Name field via &apos;Opportunity Naming Convention&apos; workflow.</description>
        <label>Job Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Number__c</fullName>
        <description>Job unique identifier/external ID populated via code.  Numbers are representative of Office, Division, PM ID, and Year.</description>
        <externalId>true</externalId>
        <label>Job Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Manager assigned to this job</description>
        <label>Project Director</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Executive Management, Project Manager</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>ATIJobpm1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Qualification</fullName>
                </value>
                <value>
                    <fullName>Estimating/Review</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                </value>
                <value>
                    <fullName>Billing Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trade__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Trade</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XACT_File_Reopened__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>XACT File Reopened</label>
        <type>Checkbox</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>ATI_Job__c</fullName>
        <label>Job</label>
        <referenceTo>ATI_Job__c</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets_PM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Budget Line Items</relationshipLabel>
        <relationshipName>Budget_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Description__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Item Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Trade__c</fullName>
        <label>Trade</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{YYYY}{MM}{DD}-{00}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata/unpackaged/classes/BudgetLWCControllerTest.cls
@isTest
Public Class BudgetLWCControllerTest{

 public static TestMethod void BudgetLwcTest()
 
 {
    
        TestDataUtil.createCustomSettings_TriggerStatus();
        
        List<user> users = TestDataUtil.createUsersNew(2, true);
        Account acc = new account(Name = 'Test Account');
        insert acc;
        List<ATI_Job__c> jobList = new List<ATI_Job__c>();
        ATI_Job__c job = new ATI_Job__c(Name = 'Test Job',Job_Name__c = 'Test Job',Job_Number__c = '1111-00',Stage__c = 'Qualification',XACT_File_Reopened__c = TRUE,Project_Manager__c =users[0].id );
        jobList.add(job);
        ATI_Job__c job2 = new ATI_Job__c(Name = 'Test Job',Job_Name__c = 'Test Job',Stage__c = 'Qualification',XACT_File_Reopened__c = FALSE,Project_Manager__c =users[0].id );
        jobList.add(job2);
        insert jobList;
        jobList[1].XACT_File_Reopened__c = TRUE;
        update jobList;
        
        Budget__c bud = new Budget__c(Name = 'Test Budget',ATI_Job__c = job.id);
        insert bud;
        
        Budget_Line_Item__c bli = new Budget_Line_Item__c(Budget__c = bud.id,Trade__c = 'FRM',Item_Description__c = '#2 &amp; better');
        insert bli;
        
        Budget_Line_Item__c bli1 = [Select id, Item_Description__c from Budget_Line_Item__c where id =: bli.id];
        
        List<Budget_Line_Item__c> blis = new List<Budget_Line_Item__c>();
        List<Id> blisIds = new List<Id>();
        blis.add(bli);
        blisIds.add(bli.id);
        blisIds.add(bli1.id);
     
        BudgetLWCController.RetrieveBudget(bud.Id);
        BudgetLWCController.RetrieveBudgetLineItems(bud.Id);
        BudgetLWCController.GetBudgetLineItemData(bli.Id);
        BudgetLWCController.RetrieveJob(bud.Id);
        BudgetLWCController.getAPINamesFromMetadata();
        BudgetLWCController.getTradeOptionPickValues();
        BudgetLWCController.UpdateBLI(blis,'10/10');
        BudgetLWCController.UpdateBLI(blis,null);
        BudgetLWCController.UpdateOnlyBLI(blis);
        BudgetLWCController.UpdateSalesTax(bud.Id, 1);
        BudgetLWCController.deleteBLI(blisIds);
        
        
    }
    
 }