metadatafullcopy/unpackaged/objects/ATI_Job__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <description>Field to note what major division/service type the job is related to.</description>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asbestos</fullName>
                </value>
                <value>
                    <fullName>Biohazard</fullName>
                </value>
                <value>
                    <fullName>Catastrophes</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contents</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Emergency Svces</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Microbial</fullName>
                </value>
                <value>
                    <fullName>Technical Svces</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Job</label>
        <referenceTo>Master_Job__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Log__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Master_Job__c.object
<CustomObject>
    <fields>
        <fullName>Asbestos_Job_Count__c</fullName>
        <label>Asbestos Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Biohazard_Job_Count__c</fullName>
        <label>Biohazard Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Catastrophes_Job_Count__c</fullName>
        <label>Catastrophes Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Construction_Job_Count__c</fullName>
        <label>Construction Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Consulting_Job_Count__c</fullName>
        <label>Consulting Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contents_Job_Count__c</fullName>
        <label>Contents Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Demolition_Job_Count__c</fullName>
        <label>Demolition Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ES_Job_Count__c</fullName>
        <label>ES Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Job_Count__c</fullName>
        <label>Lead Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Marketing_Job_Count__c</fullName>
        <label>Marketing Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Microbial_Job_Count__c</fullName>
        <label>Microbial Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Technical_Services_Job_Count__c</fullName>
        <label>Technical Services Job Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Job</label>
    <nameField>
        <label>Master Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/classes/BatchToUpdateMJDivisionCount.cls
global class BatchToUpdateMJDivisionCount implements Database.Batchable<sObject> {
  
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        return Database.getQueryLocator('Select Id, Construction_Job_Count__c, ES_Job_Count__c, Consulting_Job_Count__c, ' +
        'Contents_Job_Count__c, Asbestos_Job_Count__c, Biohazard_Job_Count__c, Catastrophes_Job_Count__c,'
        +'Demolition_Job_Count__c,Marketing_Job_Count__c, Microbial_Job_Count__c, Technical_Services_Job_Count__c, Lead_Job_Count__c'
        + ' FROM Master_Job__c' );
    }
    global void execute(Database.BatchableContext BC, List<Master_Job__c> scope)
    {
        try{
            List<Master_Job__c> masterjobs = [SELECT Id, Construction_Job_Count__c, ES_Job_Count__c, Consulting_Job_Count__c,
            Contents_Job_Count__c, Asbestos_Job_Count__c, Biohazard_Job_Count__c, Catastrophes_Job_Count__c,
            Demolition_Job_Count__c,Marketing_Job_Count__c, Microbial_Job_Count__c, Technical_Services_Job_Count__c,Lead_Job_Count__c,
            (SELECT Id, Division__c FROM Jobs__r)
            FROM Master_Job__c
            WHERE Id =:scope];
        for(Master_Job__c mj : masterjobs)
        {
            mj.Lead_Job_Count__c = 0;
            mj.Construction_Job_Count__c = 0;
            mj.Consulting_Job_Count__c = 0;
            mj.Contents_Job_Count__c = 0;
            mj.ES_Job_Count__c = 0;
            mj.Asbestos_Job_Count__c = 0;
            mj.Biohazard_Job_Count__c = 0;
            mj.Catastrophes_Job_Count__c = 0;
            mj.Demolition_Job_Count__c = 0;
            mj.Marketing_Job_Count__c = 0;
            mj.Microbial_Job_Count__c = 0;
            mj.Technical_Services_Job_Count__c = 0;
            for(ATI_Job__c job : mj.Jobs__r)
            {
                if(job.Division__c == 'Construction')
                {
                    mj.Construction_Job_Count__c += 1;
                }
                if(job.Division__c == 'Consulting')
                {
                    mj.Consulting_Job_Count__c += 1;
                }
                if(job.Division__c == 'Contents')
                {
                    mj.Contents_Job_Count__c += 1;
                }
                if(job.Division__c == 'Emergency Svces')
                {
                    mj.ES_Job_Count__c += 1;
                }
                if(job.Division__c == 'Lead')
                {
                    mj.Lead_Job_Count__c += 1;
                }
                if(job.Division__c == 'Asbestos')
                {
                    mj.Asbestos_Job_Count__c += 1;
                }
                if(job.Division__c == 'Biohazard')
                {
                    mj.Biohazard_Job_Count__c += 1;
                }
                if(job.Division__c == 'Catastrophes')
                {
                    mj.Catastrophes_Job_Count__c += 1;
                }
                if(job.Division__c == 'Demolition')
                {
                    mj.Demolition_Job_Count__c += 1;
                }
                if(job.Division__c == 'Marketing')
                {
                    mj.Marketing_Job_Count__c += 1;
                }
                if(job.Division__c == 'Microbial')
                {
                    mj.Microbial_Job_Count__c += 1;
                }
                if(job.Division__c == 'Technical Svces')
                {
                    mj.Technical_Services_Job_Count__c += 1;
                }
            }
        }
        update masterjobs;
    }catch(Exception e){
        Log__c batcherror = new Log__c( Message__c = e.getMessage());
        insert batcherror;
    }
        
    }
            
        global void finish(Database.BatchableContext BC){
        }
        }