metadatafullcopy/unpackaged/objects/Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Description__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Item Description</label>
        <type>TextArea</type>
    </fields>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BLI-{YYYY}{MM}{DD}-{00}</displayFormat>
        <label>Budget Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/BudgetLineItemFieldUpdate.cls
public without sharing class BudgetLineItemFieldUpdate {

    public static void LineItemFieldUpdate(List<Budget_Line_Item__c> LineItem){
        
        for(Budget_Line_Item__c b: LineItem){
            
            String ItemDesc = b.Item_Description__c;
            ItemDesc = ItemDesc.replaceAll('&quot;','"');
            ItemDesc = ItemDesc.replaceAll('&amp;','&');
            ItemDesc = ItemDesc.replaceAll('&apos;','\'');
            b.Item_Description__c = ItemDesc;
            
        }
    
    }
}