metadatafullcopy/unpackaged/objects/Jitterbit_Log__c.object
<CustomObject>
    <fields>
        <fullName>Log_Name__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>File Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Request Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Method__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Request Method</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Operation Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Success__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created by DemandBlue as part of Xact Integration</description>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <label>Jitterbit Log</label>
    <nameField>
        <label>Jitterbit Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jitterbit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/JitterbitBatchToPurgeLogTest.cls
/**
 * @Author: DemandBlue
 * @Description: Test Class for JitterbitBatchToPurgeLog Batch Class to Delete the Records in Jitterbit Logs object 
 * @Ver: 1.0 
**/
@isTest
Public Class JitterbitBatchToPurgeLogTest{

@isTest
Static Void testJitterBitPurge(){

       List<Jitterbit_Log__c> jitLogs = new List<Jitterbit_Log__c>();
       
       for(Integer i = 0; i<10; i++){
             
           Jitterbit_Log__c jitLog = new Jitterbit_Log__c();
           jitLog.Name = 'Log'+ i;
           jitLog.Log_Name__c  = 'Jitterbit' + i;
           jitLog.Request_Body__c = 'Test Jitterbit' + i;
           jitLog.Request_Method__c = 'GET';
           jitLog.Response__c = 'Operation has been successful';
           jitLog.Success__c = True; 
           jitLogs.add(jitLog);     
       
       }
       
       insert jitLogs;
       
       for(Jitterbit_Log__c jitLog: jitLogs){
       
           Datetime jitLogDate = Datetime.now().addDays(-120);
           Test.setCreatedDate(jitLog.Id, jitLogDate);
       } 
       
       Test.startTest();

            JitterbitBatchToPurgeLog testPurge = new JitterbitBatchToPurgeLog();
            DataBase.executeBatch(testPurge); 
            
        Test.stopTest();

  }

}