metadatafullcopy/unpackaged/objects/Location_Code__c.object
<CustomObject>
    <label>Location Code</label>
    <nameField>
        <label>Location Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/MRLocation__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asbestos</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Emergency Svces</fullName>
                </value>
                <value>
                    <fullName>Contents</fullName>
                </value>
                <value>
                    <fullName>Microbial</fullName>
                </value>
                <value>
                    <fullName>Biohazard</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Catastrophes</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Technical Svces</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsDefault__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsDefault</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Office__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Office</label>
        <referenceTo>Office__c</referenceTo>
        <relationshipLabel>MRLocations</relationshipLabel>
        <relationshipName>MRLocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MRLocation</label>
    <nameField>
        <displayFormat>MRLocation-{000}</displayFormat>
        <label>MRLocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRLocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Office__c.object
<CustomObject>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MRLocationTrigger_Test.cls
/**
 * @author           Kirankumar
 * @version          1.0
 * @date             26-07-2017
 * @status           Developed
 * @Description      Test class for MRLocation Trigger
 **/
@isTest
public class MRLocationTrigger_Test
{
     public static TestMethod void insertLocation()
     {
         //Insert Office record
         Office__c office = PRLDE_TestDataUtility.InsertOffice('Los Angeles','Westhills Court','433454','California','Southern CA');  
         
         //Inserts Location code
         Location_Code__c testLocCode = PRLDE_TestDataUtility.InsertLocationCode('TESTCODE','TEST Description');
         
         //Insert MRLocation record
         MRLocation__c mrloc = PRLDE_TestDataUtility.InsertMRLocation('Test Record',office.Id,'Consulting',true,testLocCode.Id);
     }
     
     public static TestMethod void insertLocationWthDefultChecked()
     {
         //Insert Office record
         Office__c office = PRLDE_TestDataUtility.InsertOffice('Los Angeles','Westhills Court','433454','California','Southern CA');  
         
         //Inserts Location code
         Location_Code__c testLocCode = PRLDE_TestDataUtility.InsertLocationCode('TESTCODE','TEST Description');
         
         //Insert MRLocation record
         MRLocation__c mrloc = PRLDE_TestDataUtility.InsertMRLocation('Test Record',office.Id,'Consulting',true,testLocCode.Id);
         
         //Insert MRLocation record
         MRLocation__c mrloc2 = new MRLocation__c(Office__c=office.Id,Division__c='Consulting',IsDefault__c=true);
         
         Database.SaveResult result = Database.insert(mrloc2, false);
         
         System.assertEquals(result.getErrors().size(),1);

     }
     
     public static TestMethod void UpdateLocationWthDefultChecked()
     {
         //Insert Office record
         Office__c office = PRLDE_TestDataUtility.InsertOffice('Los Angeles','Westhills Court','433454','California','Southern CA');  
         
         //Inserts Location code
         Location_Code__c testLocCode = PRLDE_TestDataUtility.InsertLocationCode('TESTCODE','TEST Description');
         
         //Insert MRLocation record
         MRLocation__c mrloc = PRLDE_TestDataUtility.InsertMRLocation('Test Record',office.Id,'Consulting',true,testLocCode.Id);
         
         //Insert MRLocation record
         MRLocation__c mrloc2 = PRLDE_TestDataUtility.InsertMRLocation('Test Record2',office.Id,'Consulting',false,testLocCode.Id);
         
         //update MRLocation record
         mrloc2.IsDefault__c = True;
         Database.SaveResult result = Database.update(mrloc2, false);
         System.assertEquals(result.getErrors().size(),1);

     }




     public static string Test(){
        Map<String, attachment> attachmentMap = new Map<String,Attachment>();
        Set<String> attachNameSet = new Set<String>();
        List<Attachment> attachments = new List<Attachment>();
        attachment a = new attachment();
        attachments.add(a);

        for(attachment attach : attachments){
            attachNameSet.add(attach.name);
            attachmentMap.put(attach.name, attach);
        }

        //query for CloudFiles
        List<CloudFiles__c> cloudFiles = [Select Id, Name FROM CloudFiles__c Where Name =: attachNameSet];
        if(!cloudFiles.isEmpty()){
        for(CloudFiles__c cloudFile : cloudFiles){
            attachmentMap.remove(cloudFile.name);

            }
        }
        
        if(!attachmentMap.isEmpty()){
            insert attachmentMap.values();
        }

     }
}