metadatafullcopy/unpackaged/objects/Master_Job__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Loss__c</fullName>
        <label>Date of Loss</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Job</label>
    <nameField>
        <label>Master Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MasterJobTriggerHandler.cls
public with sharing class MasterJobTriggerHandler {
    public static void MasterJobNameFormat(List<Master_Job__c> MasterJobs) {
        Set<Id> mjobids = new Set<Id>();
        for(Master_Job__c MasterJob : MasterJobs){

            if(MasterJob.Address_Line_1__c != null && MasterJob.City__c != null && MasterJob.State__c != null){
                MasterJob.Name = MasterJob.Address_Line_1__c + ' ' + MasterJob.City__c + ' ' + MasterJob.State__c ; 
            }
            if(MasterJob.Date_Of_Loss__c != null){
                MasterJob.Name = MasterJob.Name + ' | ' + MasterJob.Date_Of_Loss__c;
                MasterJob.Name = MasterJob.Name.replace('00:00:00', '');
               
        }
        if(MasterJob.name.length() > 79){
            MasterJob.name = MasterJob.name.substring(0, 79);
    }
        }
    }
    public static void MasterJobNameUpdate(List<Master_Job__c> newMasterJobs, map<Id,Master_Job__c> oldMasterJobs){
        for(Master_Job__c MasterJob : newMasterJobs){
            if(MasterJob.Date_Of_Loss__c != oldMasterJobs.get(MasterJob.Id).Date_Of_Loss__c && MasterJob.Date_Of_Loss__c != null){
                MasterJob.Name = MasterJob.Address_Line_1__c + ' ' + MasterJob.City__c + ' ' + MasterJob.State__c + ' | ' + MasterJob.Date_Of_Loss__c;
                MasterJob.Name = MasterJob.Name.replace('00:00:00', '');
                if(MasterJob.name.length() > 79){
                    MasterJob.name = MasterJob.name.substring(0, 79);
            }
            }
        }
    }
}