metadatafullcopy/unpackaged/objects/Master_Job__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Loss__c</fullName>
        <label>Date of Loss</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Master Jobs</relationshipLabel>
        <relationshipName>Master_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-work</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Post work</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Billing Complete</fullName>
                    <isActive>false</isActive>
                    <label>Billing Complete</label>
                </value>
                <value>
                    <fullName>Estimating/Review</fullName>
                    <isActive>false</isActive>
                    <label>Estimating/Review</label>
                </value>
                <value>
                    <fullName>Lost</fullName>
                    <isActive>false</isActive>
                    <label>Lost</label>
                </value>
                <value>
                    <fullName>Qualification</fullName>
                    <isActive>false</isActive>
                    <label>Qualification</label>
                </value>
                <value>
                    <fullName>Won</fullName>
                    <isActive>false</isActive>
                    <label>Won</label>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                    <isActive>false</isActive>
                    <label>Work Complete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Master Job</label>
    <nameField>
        <label>Master Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadatafullcopy/unpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternate_Name__c</fullName>
        <label>Alternate Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <label>Property</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MasterJobTriggerHandler_Test.cls
@isTest
public with sharing class MasterJobTriggerHandler_Test {
    static testMethod void MasterJobInsertUpdate() {
        Property__c p = new Property__c(Name = 'Test', Alternate_Name__c = 'Test Job', Address_Line_1__c = '15632 La Palma', City__c = 'Anaheim', State__c='CA');
        insert p;
        system.debug('Property is ' + p);
        Master_Job__c mj = new Master_Job__c(Name = 'Test', property__c = p.Id, Stage__c = 'Pre-work');
        insert mj;
        Master_Job__c mj1 = new Master_Job__c(Name = 'Test', Address_Line_1__c = '123', State__c = 'CA', City__c = 'Whit', Stage__c = 'Pre-work');
        insert mj1;
        system.debug('Master Job is ' + mj);
        p.Alternate_Name__c = 'Test Job 1';
        update p;
        mj.Date_of_Loss__c = system.today() + 1;
        update mj;
        mj1.Property__c = p.Id;
        update mj1;
        mj1.Date_Of_Loss__c = system.today();
        update mj1;
    }
    static testMethod void PropertyMassInsert() {
        List<Property__c> props = new List<Property__c>();
        for(Integer i = 0; i<4999;i++){
            Property__c p = new Property__c(Name = 'Test' + i, Alternate_Name__c = 'Test Job' + i, Address_Line_1__c = '15632 La Palma' + i, City__c = 'Anaheim' + i, State__c='CA');
            Property__c p1 = new Property__c(Name = 'Test' + i,  Address_Line_1__c = '15632 La Palma' + i, City__c = 'Anaheim' + i, State__c='CA');
            props.add(p);
            props.add(p1);
        }
        insert props;
       
    }
}