metadatafullcopy/unpackaged/objects/Master_Job__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Loss__c</fullName>
        <label>Date of Loss</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Address_Line_1__c</fullName>
        <formula>Property__r.Address_Line_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site Address Line 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <formula>Property__r.City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_State__c</fullName>
        <formula>Property__r.State__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Site State</label>
        <type>Text</type>
    </fields>
    <label>Master Job</label>
    <nameField>
        <label>Master Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchForMasterJobs.cls
global class BatchForMasterJobs implements Database.Batchable<sObject> {
    global String Query;
    global final String Entity;
    global final String Field;
    global final String Value;
        global Database.QueryLocator start(Database.BatchableContext BC){
         //    string pn = 'PN-'+ '%';
            query = 'Select Id, Name, Date_Of_Loss__c, Job_Address_Line_1__c, Project_Site_City__c, Project_Site_State__c FROM Master_Job__c' ;
     
         return Database.getQueryLocator(query);
 
        }
        global void execute(Database.BatchableContext BC, List<Master_Job__c> scope){
         List<Master_Job__c> props = new List<Master_Job__c>();
          for(Master_Job__c s : scope){
            
              if(s.Date_Of_Loss__c != null){
             s.Name = s.Job_Address_Line_1__c + ' ' + s.Project_Site_City__c + ' ' + s.Project_Site_State__c + ' | ' + s.Date_Of_Loss__c;
             s.Name = s.Name.replace('00:00:00', '');
             if(s.name.length() > 79){
                 s.name = s.name.substring(0, 79);
             }
              }else{
                 s.Name = s.Job_Address_Line_1__c + ' ' + s.Project_Site_City__c + ' ' + s.Project_Site_State__c;
                 s.Name = s.Name.replace('00:00:00', '');
                 if(s.name.length() > 79){
                     s.name = s.name.substring(0, 79);
                 }
              }
             props.add(s);
            }
          if(!props.isEmpty()){
             update props; 
            }
        }
         
         
         
        global void finish(Database.BatchableContext BC){
        }
     }